pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Dialogs
import Quickshell
import Quickshell.Io
import qs.modules.common
import qs.modules.common.functions

/**
 * Single owner of ~/.local/state/quickshell/user/keybinds.json.
 *
 * Hyprland shortcuts are generated by HyprlandKeybinds and never copied here.
 * This store only owns portable, user-authored pages. UI code mutates them
 * through the functions below so one atomic writer can validate every change.
 */
Singleton {
    id: root

    readonly property int schemaVersion: 2
    readonly property int maxPages: 500
    readonly property int maxKeybindsPerPage: 10000
    readonly property string filePath: Directories.keybindsPath
    readonly property string importerPath: Directories.keybindImporterPath
    readonly property string aiCategorizerPath: Directories.keybindAiCategorizerPath

    property var pages: []
    property var templates: []
    property var detectedSources: []
    property int revision: 0
    property bool ready: false
    property bool writable: false
    property bool writing: false
    property bool importing: false
    property bool scanning: false
    property bool hasScanned: false
    property bool aiCategorizing: false
    property string aiCategorizingPageId: ""
    property bool hasLoadedStore: false
    property bool storePresent: false
    property bool externalReload: false
    property bool recoveringAfterSaveFailure: false
    property bool retryAfterRecovery: false
    property string lastError: ""
    property string lastStatus: ""
    property var pendingDocument: null
    property var inFlightDocument: null
    property string inFlightText: ""
    property string lastSavedText: ""
    property int consecutiveSaveFailures: 0
    property string pendingExportPageId: ""
    property string pendingExportPageName: ""
    property real missingSince: 0
    property int missingFileGracePeriod: 2000
    property int missingFileRetryInterval: 1500

    signal pagesChangedExternally()
    signal operationFinished(bool success, string message, string pageId)

    function oneLine(value, fallback = "", limit = 160): string {
        const clean = String(value ?? "").replace(/[\r\n]+/g, " ").trim();
        return (clean || fallback).slice(0, limit);
    }

    function uniqueId(prefix): string {
        return String(prefix ?? "item") + "-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);
    }

    function clone(value): var {
        return JSON.parse(JSON.stringify(value ?? null));
    }

    function localPathFromDialogUrl(value): string {
        // FileDialog returns an encoded QUrl. FileView's textual path handling
        // strips the scheme but does not percent-decode it, so decode once and
        // pass a plain absolute path without reconstructing a file:// URL.
        return FileUtils.trimFileProtocol(decodeURIComponent(String(value ?? "")));
    }

    function normalizedEntry(value, preserveId = true): var {
        const source = value ?? ({});
        const keys = root.oneLine(source.keys ?? source.keybind ?? source.shortcut ?? source.key, "", 240);
        const description = root.oneLine(source.description ?? source.comment ?? source.label, "", 320);
        if (!keys || !description)
            return null;
        const canonicalKeys = KeybindTokenizer.canonical(keys) || keys;
        return {
            id: preserveId && root.oneLine(source.id, "", 120) ? root.oneLine(source.id, "", 120) : root.uniqueId("keybind"),
            keys: canonicalKeys,
            description: description,
            category: root.oneLine(source.category ?? source.section, "", 100),
            context: root.oneLine(source.context ?? source.when ?? source.mode, "", 180),
            notes: String(source.notes ?? source.command ?? "").replace(/[\r\n]+/g, " ").trim().slice(0, 1000),
            // Optional Material Symbol name shown before the key chips.
            // Accept common aliases so older/manual JSON stays portable.
            icon: root.oneLine(source.icon ?? source.symbol ?? source.materialIcon ?? source.iconName, "", 80),
            isBase: Boolean(source.isBase),
            isCustom: source.isCustom !== undefined ? Boolean(source.isCustom) : true,
            disabled: Boolean(source.disabled),
            created_at: Number(source.created_at) || Date.now(),
            updated_at: Number(source.updated_at) || Date.now()
        };
    }

    function normalizedPage(value, preserveIds = true): var {
        const source = value ?? ({});
        const inputEntries = Array.isArray(source.keybinds) ? source.keybinds : (Array.isArray(source.shortcuts) ? source.shortcuts : []);
        const entries = [];
        for (const candidate of inputEntries) {
            const entry = root.normalizedEntry(candidate, preserveIds);
            if (entry)
                entries.push(entry);
        }
        const usedEntryIds = new Set();
        for (const entry of entries) {
            while (usedEntryIds.has(entry.id))
                entry.id = root.uniqueId("keybind");
            usedEntryIds.add(entry.id);
        }
        return {
            id: preserveIds && root.oneLine(source.id, "", 120) ? root.oneLine(source.id, "", 120) : root.uniqueId("page"),
            name: root.oneLine(source.name ?? source.title, Translation.tr("Shortcuts"), 100),
            icon: root.oneLine(source.icon, "keyboard", 80),
            program: root.oneLine(source.program ?? source.application, "", 140),
            // Keep the friendly label above for existing exports, while the
            // desktop-entry id gives app icons a stable identity when two
            // applications share the same display name.
            programId: root.oneLine(source.programId ?? source.applicationId, "", 200),
            useProgramIcon: Boolean(source.useProgramIcon),
            sourceKind: root.oneLine(source.sourceKind ?? source.source, "manual", 60),
            sourcePath: String(source.sourcePath ?? "").trim().slice(0, 1000),
            importNote: root.oneLine(source.importNote, "", 320),
            pinned: Boolean(source.pinned),
            order: Number.isInteger(source.order) ? source.order : 0,
            baseId: root.oneLine(source.baseId, "", 120),
            isUserOverride: Boolean(source.isUserOverride),
            keybinds: entries
        };
    }

    function detectConflicts(pageId, newKeys, excludeEntryId = ""): var {
        const page = root.pageById(pageId);
        if (!page || !newKeys)
            return [];
        const canonicalTarget = KeybindTokenizer.canonical(newKeys);
        if (!canonicalTarget)
            return [];
        const conflicts = [];
        for (const entry of page.keybinds ?? []) {
            if (excludeEntryId && entry.id === excludeEntryId)
                continue;
            const canonicalEntry = KeybindTokenizer.canonical(entry.keys);
            if (canonicalEntry === canonicalTarget) {
                conflicts.push(entry);
            }
        }
        return conflicts;
    }

    function searchMatches(entry, query): bool {
        if (!entry || !query)
            return false;
        if (KeybindTokenizer.matchQuery(entry.keys, query))
            return true;
        const q = String(query).toLowerCase().trim();
        if (String(entry.description ?? "").toLowerCase().includes(q))
            return true;
        if (String(entry.category ?? "").toLowerCase().includes(q))
            return true;
        if (String(entry.context ?? "").toLowerCase().includes(q))
            return true;
        if (String(entry.notes ?? "").toLowerCase().includes(q))
            return true;
        return false;
    }

    function normalizedDocument(value, preserveIds = true): var {
        const source = value ?? ({});
        const rawPages = Array.isArray(source.pages) ? source.pages : [];
        const normalizedPages = [];
        const usedIds = new Set();
        for (const candidate of rawPages) {
            const page = root.normalizedPage(candidate, preserveIds);
            while (usedIds.has(page.id))
                page.id = root.uniqueId("page");
            usedIds.add(page.id);
            normalizedPages.push(page);
        }
        return { schemaVersion: root.schemaVersion, pages: normalizedPages };
    }

    function documentProblem(value, strictStore = false): string {
        if (!value || typeof value !== "object" || !Array.isArray(value.pages))
            return Translation.tr("Expected an object with a pages array.");
        if (value.pages.length > root.maxPages)
            return Translation.tr("The shortcut store exceeds the limit of %1 pages.").arg(String(root.maxPages));

        const pageIds = new Set();
        for (let pageIndex = 0; pageIndex < value.pages.length; pageIndex++) {
            const page = value.pages[pageIndex];
            if (!page || typeof page !== "object" || Array.isArray(page))
                return Translation.tr("Page %1 is not a valid object.").arg(String(pageIndex + 1));
            const entries = Array.isArray(page.keybinds)
                ? page.keybinds
                : (!strictStore && Array.isArray(page.shortcuts) ? page.shortcuts : null);
            if (entries === null)
                return Translation.tr("Page %1 does not contain a keybinds array.").arg(String(pageIndex + 1));
            if (entries.length > root.maxKeybindsPerPage)
                return Translation.tr("Page %1 exceeds the limit of %2 shortcuts.")
                    .arg(String(pageIndex + 1)).arg(String(root.maxKeybindsPerPage));
            if (!strictStore)
                continue;

            const pageId = root.oneLine(page.id, "", 120);
            if (!pageId || !root.oneLine(page.name, "", 100))
                return Translation.tr("Page %1 is missing its id or name.").arg(String(pageIndex + 1));
            if (pageIds.has(pageId))
                return Translation.tr("The shortcut store contains a duplicate page id.");
            pageIds.add(pageId);

            const entryIds = new Set();
            for (let entryIndex = 0; entryIndex < entries.length; entryIndex++) {
                const entry = entries[entryIndex];
                const entryId = root.oneLine(entry?.id, "", 120);
                if (!entryId || !root.normalizedEntry(entry, true))
                    return Translation.tr("Shortcut %1 on page %2 is incomplete.")
                        .arg(String(entryIndex + 1)).arg(String(pageIndex + 1));
                if (entryIds.has(entryId))
                    return Translation.tr("Page %1 contains a duplicate shortcut id.").arg(String(pageIndex + 1));
                entryIds.add(entryId);
            }
        }
        return "";
    }

    function serializedDocument(value): string {
        return JSON.stringify(root.normalizedDocument(value, true), null, 2) + "\n";
    }

    function currentDocument(): var {
        return { schemaVersion: root.schemaVersion, pages: root.clone(root.pages) ?? [] };
    }

    function publish(document, external = false): void {
        const normalized = root.normalizedDocument(document, true);
        root.pages = normalized.pages;
        root.revision++;
        if (external)
            root.pagesChangedExternally();
    }

    function loadFromDisk(): void {
        const raw = String(storeFile.text() ?? "");
        const wasRecovering = root.recoveringAfterSaveFailure;
        try {
            const parsed = JSON.parse(raw);
            const problem = root.documentProblem(parsed, true);
            if (problem)
                throw new Error(problem);
            const diskVersion = Number(parsed.schemaVersion ?? 1);
            if (!Number.isInteger(diskVersion) || diskVersion < 1 || diskVersion > root.schemaVersion)
                throw new Error("Unsupported schema version " + String(parsed.schemaVersion));

            const diskText = root.serializedDocument(parsed);
            const ownWatcherReload = root.externalReload
                && Boolean(root.lastSavedText)
                && diskText === root.lastSavedText;
            let recoveredCompletedWrite = false;
            if (wasRecovering && root.pendingDocument !== null) {
                const diskMatchesBaseline = Boolean(root.lastSavedText) && diskText === root.lastSavedText;
                const diskMatchesPending = diskText === root.serializedDocument(root.pendingDocument);
                if (!diskMatchesBaseline && !diskMatchesPending)
                    throw new Error(Translation.tr("The file changed externally while a failed save was being recovered."));
                if (diskMatchesPending) {
                    root.pendingDocument = null;
                    recoveredCompletedWrite = true;
                }
            } else if (root.externalReload && !ownWatcherReload && root.pendingDocument !== null) {
                if (diskText !== root.serializedDocument(root.pendingDocument))
                    throw new Error(Translation.tr("The file changed externally while local edits were waiting to be saved."));
                root.pendingDocument = null;
            }
            root.ready = true;
            root.writable = true;
            root.hasLoadedStore = true;
            root.storePresent = true;
            root.externalReload = false;
            root.recoveringAfterSaveFailure = false;
            root.lastSavedText = diskText;
            root.missingSince = 0;
            if (wasRecovering)
                saveRecoveryTimer.stop();
            if (!wasRecovering || recoveredCompletedWrite)
                root.lastError = "";
            if (recoveredCompletedWrite)
                root.consecutiveSaveFailures = 0;
            // A watcher reload can land between a local optimistic publish and
            // its debounced write. Never flash the older disk snapshot back
            // into the UI or leave it visible after the pending write wins.
            if (root.pendingDocument !== null) {
                root.publish(root.pendingDocument);
                if (!wasRecovering || root.retryAfterRecovery)
                    writeDebounce.restart();
            } else {
                root.publish(parsed, true);
            }
            root.retryAfterRecovery = false;
        } catch (error) {
            // Never replace malformed user data with defaults. Keeping writes
            // locked leaves the original file available for manual recovery.
            root.ready = false;
            root.writable = false;
            root.externalReload = false;
            root.recoveringAfterSaveFailure = false;
            root.retryAfterRecovery = false;
            root.lastError = Translation.tr("keybinds.json could not be loaded safely and was left untouched: %1").arg(String(error));
            root.operationFinished(false, root.lastError, "");
        }
    }

    function schedule(document): bool {
        if (!root.ready || !root.writable) {
            root.lastError = Translation.tr("Shortcut storage is not ready.");
            root.operationFinished(false, root.lastError, "");
            return false;
        }
        const problem = root.documentProblem(document, false);
        if (problem) {
            root.lastError = problem;
            root.operationFinished(false, problem, "");
            return false;
        }
        const normalized = root.normalizedDocument(document, true);
        // Publish immediately so rapid consecutive edits build on the newest
        // snapshot instead of racing the debounce that persists it.
        root.pendingDocument = normalized;
        root.publish(normalized);
        writeDebounce.restart();
        return true;
    }

    function flush(): bool {
        if (!root.ready || !root.writable || root.writing || root.recoveringAfterSaveFailure || root.pendingDocument === null)
            return false;
        const next = root.pendingDocument;
        const encoded = root.serializedDocument(next);
        if (root.storePresent && encoded === String(storeFile.text() ?? "")) {
            root.pendingDocument = null;
            root.lastError = "";
            return true;
        }
        root.pendingDocument = null;
        root.inFlightDocument = next;
        root.inFlightText = encoded;
        root.writing = true;
        storeFile.setText(encoded);
        return true;
    }

    function reload(): void {
        storeFile.reload();
    }

    function indexOfPage(pageId): int {
        const wanted = String(pageId ?? "");
        for (let i = 0; i < root.pages.length; i++) {
            if (String(root.pages[i]?.id ?? "") === wanted)
                return i;
        }
        return -1;
    }

    function pageById(pageId): var {
        const index = root.indexOfPage(pageId);
        return index >= 0 ? root.pages[index] : null;
    }

    function uniquePageName(requested, exceptPageId = ""): string {
        const base = root.oneLine(requested, Translation.tr("Shortcuts"), 100);
        const names = new Set(root.pages
            .filter(page => String(page.id ?? "") !== String(exceptPageId ?? ""))
            .map(page => String(page.name ?? "").toLowerCase()));
        if (!names.has(base.toLowerCase()))
            return base;
        let suffix = 2;
        while (names.has((base + " " + suffix).toLowerCase()))
            suffix++;
        return base + " " + suffix;
    }

    function createPage(name, icon = "keyboard", program = "", entries = [], metadata = null): string {
        if (root.pages.length >= root.maxPages) {
            const message = Translation.tr("The shortcut store already contains the maximum of %1 pages.").arg(String(root.maxPages));
            root.operationFinished(false, message, "");
            return "";
        }
        const pages = root.clone(root.pages) ?? [];
        const source = metadata ?? ({});
        const page = root.normalizedPage({
            name: root.uniquePageName(name),
            icon: icon,
            program: program,
            programId: root.oneLine(source.programId ?? source.applicationId, "", 200),
            useProgramIcon: Boolean(source.useProgramIcon),
            sourceKind: source.sourceKind ?? "manual",
            sourcePath: source.sourcePath ?? "",
            importNote: source.importNote ?? "",
            keybinds: entries
        }, false);
        pages.push(page);
        if (!root.schedule({ schemaVersion: root.schemaVersion, pages: pages }))
            return "";
        root.lastStatus = Translation.tr("Created %1.").arg(String(page.name));
        root.operationFinished(true, root.lastStatus, page.id);
        return page.id;
    }

    function updatePage(pageId, name, icon, program, useProgramIcon = false, programId = ""): bool {
        const pages = root.clone(root.pages) ?? [];
        const index = pages.findIndex(page => page.id === pageId);
        if (index < 0)
            return false;
        pages[index].name = root.uniquePageName(root.oneLine(name, pages[index].name, 100), pageId);
        pages[index].icon = root.oneLine(icon, "keyboard", 80);
        pages[index].program = root.oneLine(program, "", 140);
        pages[index].programId = root.oneLine(programId, "", 200);
        pages[index].useProgramIcon = Boolean(useProgramIcon);
        return root.schedule({ schemaVersion: root.schemaVersion, pages: pages });
    }

    function setPageKeybinds(pageId, keybinds): bool {
        const pages = root.clone(root.pages) ?? [];
        const index = pages.findIndex(page => page.id === pageId);
        if (index < 0)
            return false;
        pages[index].keybinds = (keybinds ?? []).map(entry => root.normalizedEntry(entry, Boolean(entry?.id))).filter(Boolean);
        return root.schedule({ schemaVersion: root.schemaVersion, pages: pages });
    }

    function deletePage(pageId): bool {
        const pages = root.clone(root.pages) ?? [];
        const index = pages.findIndex(page => page.id === pageId);
        if (index < 0)
            return false;
        const removedName = String(pages[index].name ?? Translation.tr("Shortcuts"));
        pages.splice(index, 1);
        const accepted = root.schedule({ schemaVersion: root.schemaVersion, pages: pages });
        if (accepted) {
            root.lastStatus = Translation.tr("Deleted %1.").arg(removedName);
            root.operationFinished(true, root.lastStatus, "");
        }
        return accepted;
    }

    function addKeybind(pageId, keys, description, category = "", context = "", notes = "", icon = ""): string {
        const pages = root.clone(root.pages) ?? [];
        const index = pages.findIndex(page => page.id === pageId);
        if (index < 0)
            return "";
        if (pages[index].keybinds.length >= root.maxKeybindsPerPage) {
            const message = Translation.tr("This page already contains the maximum of %1 shortcuts.").arg(String(root.maxKeybindsPerPage));
            root.operationFinished(false, message, pageId);
            return "";
        }
        const entry = root.normalizedEntry({ keys, description, category, context, notes, icon }, false);
        if (!entry)
            return "";
        pages[index].keybinds.push(entry);
        if (!root.schedule({ schemaVersion: root.schemaVersion, pages: pages }))
            return "";
        return entry.id;
    }

    function updateKeybind(pageId, keybindId, keys, description, category = "", context = "", notes = "", icon = ""): bool {
        const pages = root.clone(root.pages) ?? [];
        const pageIndex = pages.findIndex(page => page.id === pageId);
        if (pageIndex < 0)
            return false;
        const entryIndex = pages[pageIndex].keybinds.findIndex(entry => entry.id === keybindId);
        if (entryIndex < 0)
            return false;
        const entry = root.normalizedEntry({ id: keybindId, keys, description, category, context, notes, icon }, true);
        if (!entry)
            return false;
        pages[pageIndex].keybinds[entryIndex] = entry;
        return root.schedule({ schemaVersion: root.schemaVersion, pages: pages });
    }

    function deleteKeybind(pageId, keybindId): bool {
        const pages = root.clone(root.pages) ?? [];
        const pageIndex = pages.findIndex(page => page.id === pageId);
        if (pageIndex < 0)
            return false;
        const entryIndex = pages[pageIndex].keybinds.findIndex(entry => entry.id === keybindId);
        if (entryIndex < 0)
            return false;
        pages[pageIndex].keybinds.splice(entryIndex, 1);
        return root.schedule({ schemaVersion: root.schemaVersion, pages: pages });
    }

    function createFromTemplate(templateId): string {
        const template = root.templates.find(candidate => candidate.id === templateId);
        if (!template)
            return "";
        return root.createPage(template.name, template.icon, template.program, template.keybinds, {
            sourceKind: "template",
            importNote: Translation.tr("Starter collection — customize it for your setup."),
            programId: String(template.programId ?? ""),
            useProgramIcon: Boolean(template.useProgramIcon)
        });
    }

    function importPayload(payload, suggestedName = Translation.tr("Imported shortcuts")): string {
        if (payload && !Array.isArray(payload) && payload.schemaVersion !== undefined) {
            const importedVersion = Number(payload.schemaVersion);
            if (!Number.isInteger(importedVersion) || importedVersion < 1 || importedVersion > root.schemaVersion) {
                root.operationFinished(false, Translation.tr("Unsupported shortcut JSON schema version."), "");
                return "";
            }
        }
        let candidates = [];
        if (Array.isArray(payload)) {
            candidates = [{ name: suggestedName, icon: "keyboard", keybinds: payload }];
        } else if (payload?.page) {
            candidates = [payload.page];
        } else if (Array.isArray(payload?.pages)) {
            candidates = payload.pages;
        } else if (Array.isArray(payload?.keybinds) || Array.isArray(payload?.shortcuts)) {
            candidates = [payload];
        } else {
            root.operationFinished(false, Translation.tr("Unsupported JSON format."), "");
            return "";
        }

        const pages = root.clone(root.pages) ?? [];
        const usedNames = new Set(pages.map(page => String(page.name ?? "").toLowerCase()));
        let firstId = "";
        let importedCount = 0;
        if (pages.length + candidates.length > root.maxPages) {
            root.operationFinished(false, Translation.tr("Importing these pages would exceed the %1-page limit.").arg(String(root.maxPages)), "");
            return "";
        }
        for (const candidate of candidates) {
            if (!candidate || typeof candidate !== "object" || Array.isArray(candidate))
                continue;
            const rawEntries = Array.isArray(candidate.keybinds)
                ? candidate.keybinds
                : (Array.isArray(candidate.shortcuts) ? candidate.shortcuts : null);
            if (rawEntries === null)
                continue;
            if (rawEntries.length > root.maxKeybindsPerPage) {
                root.operationFinished(false, Translation.tr("An imported page exceeds the %1-shortcut limit.").arg(String(root.maxKeybindsPerPage)), "");
                return "";
            }
            const page = root.normalizedPage(candidate, false);
            // An explicitly empty page is valid and must survive an
            // export/import round trip. A non-empty array with no valid
            // keybinds is still rejected as malformed input.
            if (rawEntries.length > 0 && page.keybinds.length === 0)
                continue;
            const baseName = root.oneLine(page.name, suggestedName, 100);
            let uniqueName = baseName;
            let suffix = 2;
            while (usedNames.has(uniqueName.toLowerCase()))
                uniqueName = baseName + " " + suffix++;
            usedNames.add(uniqueName.toLowerCase());
            page.name = uniqueName;
            if (!page.sourceKind || page.sourceKind === "manual")
                page.sourceKind = "json";
            pages.push(page);
            if (!firstId)
                firstId = page.id;
            importedCount++;
        }
        if (importedCount === 0) {
            root.operationFinished(false, Translation.tr("No valid shortcuts were found."), "");
            return "";
        }
        if (!root.schedule({ schemaVersion: root.schemaVersion, pages: pages }))
            return "";
        root.operationFinished(true, Translation.tr("Imported %1 page(s).").arg(String(importedCount)), firstId);
        return firstId;
    }

    function openImportDialog(): void {
        if (importPickerProcess.running)
            return;
        importPickerProcess.command = [
            "bash", "-c",
            "FILE=\"\"; "
            + "if command -v kdialog >/dev/null 2>&1; then FILE=$(kdialog --getopenfilename \"$HOME/Documents\" \"*.json\" 2>/dev/null || true); "
            + "elif command -v zenity >/dev/null 2>&1; then FILE=$(zenity --file-selection --filename=\"$HOME/Documents/\" --file-filter=\"JSON files (*.json) | *.json\" --file-filter=\"All files | *\" 2>/dev/null || true); "
            + "elif command -v yad >/dev/null 2>&1; then FILE=$(yad --file --filename=\"$HOME/Documents/\" --file-filter=\"JSON files (*.json) | *.json\" 2>/dev/null || true); fi; "
            + "if [ -n \"$FILE\" ]; then printf '%s' \"$FILE\"; fi"
        ];
        importPickerProcess.running = true;
    }

    function openExportDialog(pageId): void {
        const page = root.pageById(pageId);
        if (!page)
            return;
        root.pendingExportPageId = pageId;
        root.pendingExportPageName = String(page.name ?? Translation.tr("Shortcuts"));
        const safeName = String(page.name ?? "shortcuts").toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "shortcuts";
        exportDialog.selectedFile = Directories.documents + "/" + safeName + ".json";
        exportDialog.open();
    }

    function exportPageToPath(pageId, path): bool {
        const page = root.pageById(pageId);
        if (!page)
            return false;
        const targetPath = root.localPathFromDialogUrl(path);
        if (!targetPath)
            return false;
        exportFile.path = targetPath;
        const portablePage = root.clone(page);
        // Absolute source paths are useful locally for provenance, but should
        // not leak a home-directory layout into a file intended for sharing.
        portablePage.sourcePath = "";
        exportFile.setText(JSON.stringify({ schemaVersion: root.schemaVersion, page: portablePage }, null, 2) + "\n");
        return true;
    }

    function scanKnownPrograms(): void {
        if (root.scanning)
            return;
        root.scanning = true;
        root.detectedSources = [];
        scanProcess.command = ["python3", root.importerPath, "scan"];
        scanProcess.running = true;
    }

    function importDetectedSource(source): void {
        if (root.importing || !source)
            return;
        root.importing = true;
        detectedImportProcess.running = false;
        detectedImportProcess.command = ["python3", root.importerPath, "import", String(source.kind ?? ""), String(source.path ?? "")];
        detectedImportProcess.running = true;
    }

    function aiCategorizePage(pageId, modelId = "", lang = ""): void {
        if (root.aiCategorizing || !pageId)
            return;
        const page = root.pageById(pageId);
        if (!page || (page.keybinds ?? []).length === 0)
            return;
        root.aiCategorizing = true;
        root.aiCategorizingPageId = String(pageId);
        const activeModel = String(modelId || (typeof Ai !== "undefined" ? Ai.currentModelId : "")).trim();
        const activeLang = String(lang || (typeof Translation !== "undefined" ? Translation.languageCode : "")).trim();
        const cmd = ["python3", root.aiCategorizerPath, String(pageId), "--file", root.filePath];
        if (activeModel) {
            cmd.push("--model", activeModel);
        }
        if (activeLang) {
            cmd.push("--lang", activeLang);
        }
        aiCategorizeTimeoutTimer.restart();
        aiCategorizeProcess.running = false;
        aiCategorizeProcess.command = cmd;
        aiCategorizeProcess.running = true;
    }

    Timer {
        id: writeDebounce
        interval: 150
        repeat: false
        onTriggered: root.flush()
    }

    Timer {
        id: saveRecoveryTimer
        interval: root.missingFileRetryInterval
        repeat: false
        onTriggered: storeFile.reload()
    }

    Timer {
        id: externalReloadDebounce
        interval: 180
        repeat: false
        onTriggered: {
            if (root.writing) {
                restart();
                return;
            }
            storeFile.reload();
        }
    }

    Timer {
        id: missingFileRetryTimer
        interval: root.missingFileRetryInterval
        repeat: false
        onTriggered: root.reload()
    }

    FileDialog {
        id: importDialog
        parentWindow: null
        title: Translation.tr("Import shortcut pages")
        currentFolder: Directories.documents
        fileMode: FileDialog.OpenFile
        nameFilters: [Translation.tr("JSON files (*.json)"), Translation.tr("All files (*)")]
        onAccepted: {
            importFile.path = root.localPathFromDialogUrl(selectedFile);
            importFile.reload();
        }
    }

    FileDialog {
        id: exportDialog
        parentWindow: null
        title: Translation.tr("Export shortcut page")
        currentFolder: Directories.documents
        fileMode: FileDialog.SaveFile
        defaultSuffix: "json"
        nameFilters: [Translation.tr("JSON files (*.json)")]
        onAccepted: root.exportPageToPath(root.pendingExportPageId, selectedFile.toString())
    }

    FileView {
        id: storeFile
        path: Qt.resolvedUrl(root.filePath)
        watchChanges: true
        atomicWrites: true
        onLoaded: root.loadFromDisk()
        onSaved: {
            root.writing = false;
            root.inFlightDocument = null;
            root.lastSavedText = root.inFlightText;
            root.inFlightText = "";
            root.storePresent = true;
            root.consecutiveSaveFailures = 0;
            root.lastError = "";
            // Keep consecutive optimistic edits ordered. Starting the newest
            // queued snapshot immediately also prevents the file watcher from
            // mistaking our previous atomic write for an external conflict.
            if (root.pendingDocument !== null)
                root.flush();
        }
        onSaveFailed: error => {
            const failedDocument = root.inFlightDocument;
            root.writing = false;
            root.inFlightDocument = null;
            root.inFlightText = "";
            if (root.pendingDocument === null && failedDocument !== null)
                root.pendingDocument = failedDocument;
            root.consecutiveSaveFailures++;
            root.recoveringAfterSaveFailure = true;
            root.retryAfterRecovery = root.consecutiveSaveFailures < 3;
            root.externalReload = false;
            externalReloadDebounce.stop();
            root.lastError = Translation.tr("Could not save shortcut storage (error %1). Your edits remain in memory.").arg(String(error));
            root.operationFinished(false, root.lastError, "");
            // setText() leaves the attempted contents cached in FileView even
            // on failure. Reload the actual file before retrying so equality
            // checks and change notification remain meaningful.
            saveRecoveryTimer.restart();
        }
        onFileChanged: {
            root.externalReload = true;
            if (!root.writing && root.pendingDocument !== null)
                writeDebounce.stop();
            externalReloadDebounce.restart();
        }
        onLoadFailed: error => {
            root.externalReload = false;
            if (error !== FileViewError.FileNotFound) {
                root.ready = false;
                root.writable = false;
                root.recoveringAfterSaveFailure = false;
                root.retryAfterRecovery = false;
                root.lastError = Translation.tr("Could not load shortcut storage (error %1).").arg(String(error));
                root.operationFinished(false, root.lastError, "");
                return;
            }
            root.storePresent = false;
            const now = Date.now();
            if (root.missingSince <= 0) {
                root.missingSince = now;
                root.ready = false;
                root.writable = false;
                missingFileRetryTimer.restart();
            } else if (now - root.missingSince >= root.missingFileGracePeriod) {
                root.ready = true;
                root.writable = true;
                root.recoveringAfterSaveFailure = false;
                root.retryAfterRecovery = false;
                const replacement = root.pendingDocument !== null
                    ? root.pendingDocument
                    : (root.hasLoadedStore ? root.currentDocument() : { schemaVersion: root.schemaVersion, pages: [] });
                root.publish(replacement);
                root.pendingDocument = replacement;
                root.flush();
            } else {
                missingFileRetryTimer.restart();
            }
        }
    }

    FileView {
        id: templatesFile
        path: Qt.resolvedUrl(Directories.keybindTemplatesPath)
        onLoaded: {
            try {
                const parsed = JSON.parse(templatesFile.text());
                root.templates = Array.isArray(parsed?.templates) ? parsed.templates.map(item => root.normalizedPage(item, true)) : [];
            } catch (error) {
                root.templates = [];
                console.error("[KeybindsService] Could not load templates:", error);
            }
        }
    }

    FileView {
        id: importFile
        path: ""
        onLoaded: {
            try {
                const parsed = JSON.parse(importFile.text());
                const encodedName = FileUtils.fileNameForPath(importFile.path);
                const fileName = FileUtils.trimFileExt(encodedName);
                root.importPayload(parsed, fileName || Translation.tr("Imported shortcuts"));
            } catch (error) {
                root.operationFinished(false, Translation.tr("Could not parse JSON: %1").arg(String(error)), "");
            }
        }
        onLoadFailed: error => root.operationFinished(false, Translation.tr("Could not read the selected file (error %1).").arg(String(error)), "")
    }

    FileView {
        id: exportFile
        path: ""
        atomicWrites: true
        onSaved: {
            root.lastStatus = Translation.tr("Exported %1.").arg(root.pendingExportPageName);
            root.operationFinished(true, root.lastStatus, root.pendingExportPageId);
        }
        onSaveFailed: error => root.operationFinished(false, Translation.tr("Could not export shortcuts (error %1).").arg(String(error)), root.pendingExportPageId)
    }

    Process {
        id: importPickerProcess
        stdout: StdioCollector {
            id: pickerCollector
            onStreamFinished: {
                const selectedPath = String(pickerCollector.text ?? "").trim();
                if (!selectedPath)
                    return;
                importFile.path = selectedPath;
                importFile.reload();
            }
        }
    }

    Process {
        id: scanProcess
        stdout: StdioCollector {
            id: scanCollector
        }
        stderr: StdioCollector {
            id: scanErrorCollector
        }
        onExited: (exitCode, exitStatus) => {
            root.scanning = false;
            root.hasScanned = true;
            try {
                const raw = (scanCollector.text || "").trim();
                const reply = JSON.parse(raw || "{}");
                root.detectedSources = Array.isArray(reply.sources) ? reply.sources : [];
                if (!reply.ok)
                    root.operationFinished(false, String(reply.error ?? Translation.tr("Could not scan applications.")), "");
            } catch (error) {
                console.error("[KeybindsService] scan error:", error, scanErrorCollector.text, scanCollector.text);
                root.operationFinished(false, Translation.tr("Could not read scan results: %1").arg(String(error)), "");
            }
        }
    }

    Process {
        id: detectedImportProcess
        stdout: StdioCollector {
            id: importCollector
        }
        stderr: StdioCollector {
            id: importErrorCollector
        }
        onExited: (exitCode, exitStatus) => {
            root.importing = false;
            try {
                const raw = (importCollector.text || "").trim();
                const reply = JSON.parse(raw || "{}");
                if (!reply.ok) {
                    root.operationFinished(false, String(reply.error ?? Translation.tr("Automatic import failed.")), "");
                    return;
                }
                root.importPayload({ page: reply.page }, String(reply.page?.name ?? Translation.tr("Imported shortcuts")));
            } catch (error) {
                console.error("[KeybindsService] import error:", error, importErrorCollector.text, importCollector.text);
                root.operationFinished(false, Translation.tr("Could not read import results: %1").arg(String(error)), "");
            }
        }
    }

    Timer {
        id: aiCategorizeTimeoutTimer
        interval: 180000 // 3 minutes timeout
        repeat: false
        onTriggered: {
            if (root.aiCategorizing) {
                const targetPageId = root.aiCategorizingPageId;
                root.aiCategorizing = false;
                root.aiCategorizingPageId = "";
                aiCategorizeProcess.running = false;
                const pageName = root.pageById(targetPageId)?.name || Translation.tr("Shortcuts");
                const errMsg = Translation.tr("AI request timed out after 3 minutes. The model did not respond.");
                root.operationFinished(false, errMsg, targetPageId);
                Quickshell.execDetached(["notify-send", Translation.tr("Keybinding categorization failed"), pageName + ": " + errMsg, "-a", "Cheatsheet", "-i", "error", "-u", "critical"]);
            }
        }
    }

    Process {
        id: aiCategorizeProcess
        stdout: StdioCollector {
            id: aiCategorizeCollector
        }
        stderr: StdioCollector {
            id: aiCategorizeErrorCollector
        }
        onExited: (exitCode, exitStatus) => {
            aiCategorizeTimeoutTimer.stop();
            const targetPageId = root.aiCategorizingPageId;
            root.aiCategorizing = false;
            root.aiCategorizingPageId = "";
            const pageName = root.pageById(targetPageId)?.name || Translation.tr("Shortcuts");
            try {
                const raw = (aiCategorizeCollector.text || "").trim();
                const reply = JSON.parse(raw || "{}");
                if (!reply.ok) {
                    const errMsg = String(reply.error ?? aiCategorizeErrorCollector.text ?? Translation.tr("AI categorization failed."));
                    root.operationFinished(false, errMsg, targetPageId);
                    Quickshell.execDetached(["notify-send", Translation.tr("Keybinding categorization failed"), pageName + ": " + errMsg, "-a", "Cheatsheet", "-i", "error", "-u", "critical"]);
                    return;
                }
                const updatedKeybinds = Array.isArray(reply.keybinds) ? reply.keybinds : [];
                if (targetPageId && updatedKeybinds.length > 0) {
                    const saved = root.setPageKeybinds(targetPageId, updatedKeybinds);
                    if (saved) {
                        root.flush();
                        const successMsg = Translation.tr("Shortcuts categorized into %1 groups with AI.").arg(String(reply.categoryCount ?? 1));
                        root.operationFinished(true, successMsg, targetPageId);
                        Quickshell.execDetached(["notify-send", Translation.tr("Keybindings categorized"), Translation.tr("Successfully organized shortcuts for %1 with AI (%2 categories).").arg(pageName).arg(String(reply.categoryCount ?? 1)), "-a", "Cheatsheet", "-i", "keyboard"]);
                    } else {
                        const errMsg = Translation.tr("Failed to save categorized shortcuts.");
                        root.operationFinished(false, errMsg, targetPageId);
                        Quickshell.execDetached(["notify-send", Translation.tr("Keybinding categorization failed"), pageName + ": " + errMsg, "-a", "Cheatsheet", "-i", "error", "-u", "critical"]);
                    }
                } else {
                    const errMsg = Translation.tr("No keybindings returned by AI.");
                    root.operationFinished(false, errMsg, targetPageId);
                    Quickshell.execDetached(["notify-send", Translation.tr("Keybinding categorization failed"), pageName + ": " + errMsg, "-a", "Cheatsheet", "-i", "error", "-u", "critical"]);
                }
            } catch (error) {
                console.error("[KeybindsService] AI categorize error:", error, aiCategorizeErrorCollector.text, aiCategorizeCollector.text);
                const errMsg = String(error) + (aiCategorizeErrorCollector.text ? (" - " + aiCategorizeErrorCollector.text) : "");
                root.operationFinished(false, Translation.tr("AI error: %1").arg(errMsg), targetPageId);
                Quickshell.execDetached(["notify-send", Translation.tr("Keybinding categorization failed"), pageName + ": " + errMsg, "-a", "Cheatsheet", "-i", "error", "-u", "critical"]);
            }
        }
    }

    Component.onCompleted: {
        storeFile.reload();
        templatesFile.reload();
    }
}
