#!/usr/bin/env python3
"""
Generate comprehensive, ready-made keybind collections for popular editors, TUIs,
terminal emulators, multiplexers, and developer tools.
"""

import json
from pathlib import Path

TEMPLATES = [
    {
        "id": "template-vscode",
        "name": "Visual Studio Code",
        "icon": "code",
        "program": "Visual Studio Code",
        "programId": "code",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+Shift+P", "description": "Show command palette", "category": "General"},
            {"keys": "Ctrl+P", "description": "Quick open / Go to file", "category": "Navigation"},
            {"keys": "Ctrl+Shift+N", "description": "New window / instance", "category": "General"},
            {"keys": "Ctrl+Shift+W", "description": "Close window", "category": "General"},
            {"keys": "Ctrl+,", "description": "Open user settings", "category": "General"},
            {"keys": "Ctrl+K Ctrl+S", "description": "Open keyboard shortcuts", "category": "General"},
            {"keys": "Ctrl+N", "description": "New untitled file", "category": "File Management"},
            {"keys": "Ctrl+O", "description": "Open file dialog", "category": "File Management"},
            {"keys": "Ctrl+S", "description": "Save current file", "category": "File Management"},
            {"keys": "Ctrl+Shift+S", "description": "Save all files", "category": "File Management"},
            {"keys": "Ctrl+W", "description": "Close active editor", "category": "File Management"},
            {"keys": "Ctrl+K Ctrl+W", "description": "Close all open editors", "category": "File Management"},
            {"keys": "Ctrl+Shift+T", "description": "Reopen last closed editor", "category": "File Management"},
            {"keys": "Ctrl+K Enter", "description": "Keep preview editor open", "category": "File Management"},
            {"keys": "Ctrl+Tab", "description": "Switch to next editor in group", "category": "Navigation"},
            {"keys": "Ctrl+Shift+Tab", "description": "Switch to previous editor in group", "category": "Navigation"},
            {"keys": "Ctrl+1", "description": "Focus first editor group", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+2", "description": "Focus second editor group", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+3", "description": "Focus third editor group", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+K Ctrl+Right", "description": "Move active editor into right group", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+K Ctrl+Left", "description": "Move active editor into left group", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+\\", "description": "Split editor horizontally / vertically", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+K Left", "description": "Focus editor group on left", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+K Right", "description": "Focus editor group on right", "category": "Window & Editor Groups"},
            {"keys": "Ctrl+X", "description": "Cut current line (empty selection)", "category": "Editing"},
            {"keys": "Ctrl+C", "description": "Copy current line (empty selection)", "category": "Editing"},
            {"keys": "Ctrl+V", "description": "Paste clipboard content", "category": "Editing"},
            {"keys": "Alt+Up", "description": "Move line / selection up", "category": "Editing"},
            {"keys": "Alt+Down", "description": "Move line / selection down", "category": "Editing"},
            {"keys": "Shift+Alt+Up", "description": "Duplicate line / selection up", "category": "Editing"},
            {"keys": "Shift+Alt+Down", "description": "Duplicate line / selection down", "category": "Editing"},
            {"keys": "Ctrl+Shift+K", "description": "Delete entire line", "category": "Editing"},
            {"keys": "Ctrl+Enter", "description": "Insert line below cursor", "category": "Editing"},
            {"keys": "Ctrl+Shift+Enter", "description": "Insert line above cursor", "category": "Editing"},
            {"keys": "Ctrl+Shift+\\", "description": "Jump to matching bracket", "category": "Editing"},
            {"keys": "Ctrl+]", "description": "Indent current line", "category": "Editing"},
            {"keys": "Ctrl+[", "description": "Outdent current line", "category": "Editing"},
            {"keys": "Ctrl+/", "description": "Toggle line comment", "category": "Editing"},
            {"keys": "Shift+Alt+A", "description": "Toggle block comment", "category": "Editing"},
            {"keys": "Alt+Z", "description": "Toggle word wrap", "category": "View & Layout"},
            {"keys": "Ctrl+Alt+Up", "description": "Insert multi-cursor above", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+Alt+Down", "description": "Insert multi-cursor below", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+D", "description": "Select next matching word occurrence", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+K Ctrl+D", "description": "Skip current match and pick next", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+U", "description": "Undo last cursor action", "category": "Multi-Cursor & Selection"},
            {"keys": "Shift+Alt+I", "description": "Insert cursor at end of each selected line", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+Shift+L", "description": "Select all occurrences of current find match", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+F2", "description": "Select all occurrences of current word", "category": "Multi-Cursor & Selection"},
            {"keys": "Shift+Alt+Right", "description": "Smart expand selection", "category": "Multi-Cursor & Selection"},
            {"keys": "Shift+Alt+Left", "description": "Smart shrink selection", "category": "Multi-Cursor & Selection"},
            {"keys": "Ctrl+F", "description": "Find in current file", "category": "Search & Replace"},
            {"keys": "Ctrl+H", "description": "Replace in current file", "category": "Search & Replace"},
            {"keys": "F3", "description": "Find next match", "category": "Search & Replace"},
            {"keys": "Shift+F3", "description": "Find previous match", "category": "Search & Replace"},
            {"keys": "Ctrl+Shift+F", "description": "Global find in project files", "category": "Search & Replace"},
            {"keys": "Ctrl+Shift+H", "description": "Global replace in project files", "category": "Search & Replace"},
            {"keys": "Alt+C", "description": "Toggle case-sensitive match", "category": "Search & Replace"},
            {"keys": "Alt+R", "description": "Toggle regex mode in search", "category": "Search & Replace"},
            {"keys": "Alt+W", "description": "Toggle match whole word", "category": "Search & Replace"},
            {"keys": "F12", "description": "Go to definition", "category": "Code Navigation & Refactoring"},
            {"keys": "Alt+F12", "description": "Peek definition without jumping", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+K F12", "description": "Open definition to the side", "category": "Code Navigation & Refactoring"},
            {"keys": "Shift+F12", "description": "Show all references", "category": "Code Navigation & Refactoring"},
            {"keys": "F2", "description": "Rename symbol project-wide", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+.", "description": "Quick fix / code actions", "category": "Code Navigation & Refactoring"},
            {"keys": "Shift+Alt+F", "description": "Format entire document", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+K Ctrl+F", "description": "Format selected code", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+Space", "description": "Trigger IntelliSense completion", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+Shift+Space", "description": "Trigger parameter hints tooltip", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+T", "description": "Go to symbol in workspace", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+Shift+O", "description": "Go to symbol in current file", "category": "Code Navigation & Refactoring"},
            {"keys": "Ctrl+G", "description": "Go to line number", "category": "Navigation"},
            {"keys": "Alt+Left", "description": "Navigate back in edit history", "category": "Navigation"},
            {"keys": "Alt+Right", "description": "Navigate forward in edit history", "category": "Navigation"},
            {"keys": "F8", "description": "Go to next error or warning", "category": "Diagnostics"},
            {"keys": "Shift+F8", "description": "Go to previous error or warning", "category": "Diagnostics"},
            {"keys": "Ctrl+Shift+M", "description": "Toggle problems & diagnostics panel", "category": "Diagnostics"},
            {"keys": "Ctrl+`", "description": "Toggle integrated terminal", "category": "Terminal"},
            {"keys": "Ctrl+Shift+`", "description": "Create new integrated terminal instance", "category": "Terminal"},
            {"keys": "Ctrl+Shift+C", "description": "Copy selection in terminal", "category": "Terminal"},
            {"keys": "Ctrl+Shift+V", "description": "Paste into integrated terminal", "category": "Terminal"},
            {"keys": "Ctrl+B", "description": "Toggle primary sidebar", "category": "View & Layout"},
            {"keys": "Ctrl+Shift+E", "description": "Show explorer sidebar view", "category": "View & Layout"},
            {"keys": "Ctrl+Shift+X", "description": "Show extensions marketplace view", "category": "View & Layout"},
            {"keys": "Ctrl+Shift+G", "description": "Show Source Control (Git) view", "category": "Source Control"},
            {"keys": "Ctrl+Shift+D", "description": "Show Run & Debug sidebar view", "category": "Debugging"},
            {"keys": "Ctrl+J", "description": "Toggle bottom panel", "category": "View & Layout"},
            {"keys": "F5", "description": "Start debugging / Continue execution", "category": "Debugging"},
            {"keys": "Ctrl+F5", "description": "Run without debugging", "category": "Debugging"},
            {"keys": "Shift+F5", "description": "Stop debugging session", "category": "Debugging"},
            {"keys": "Ctrl+Shift+F5", "description": "Restart debugging session", "category": "Debugging"},
            {"keys": "F9", "description": "Toggle breakpoint on current line", "category": "Debugging"},
            {"keys": "F10", "description": "Step over current function call", "category": "Debugging"},
            {"keys": "F11", "description": "Step into function call", "category": "Debugging"},
            {"keys": "Shift+F11", "description": "Step out of current function", "category": "Debugging"}
        ]
    },
    {
        "id": "template-neovim",
        "name": "Neovim",
        "icon": "terminal",
        "program": "Neovim",
        "programId": "nvim",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "h", "description": "Move cursor left", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "j", "description": "Move cursor down", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "k", "description": "Move cursor up", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "l", "description": "Move cursor right", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "w", "description": "Jump forward to start of next word", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "b", "description": "Jump backward to start of previous word", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "e", "description": "Jump forward to end of current word", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "ge", "description": "Jump backward to end of previous word", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "W", "description": "Jump forward to start of next WORD (space-delimited)", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "B", "description": "Jump backward to start of previous WORD", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "0", "description": "Jump to beginning of current line", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "^", "description": "Jump to first non-blank character of line", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "$", "description": "Jump to end of line", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "gg", "description": "Jump to first line of file", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "G", "description": "Jump to last line of file (or [count]G)", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "%", "description": "Jump to matching bracket (), [], {}", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "Ctrl+U", "description": "Scroll half-page up and keep cursor centered", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "Ctrl+D", "description": "Scroll half-page down and keep cursor centered", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "Ctrl+B", "description": "Scroll full page backward", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "Ctrl+F", "description": "Scroll full page forward", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "H", "description": "Jump to top of screen (High)", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "M", "description": "Jump to middle of screen (Middle)", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "L", "description": "Jump to bottom of screen (Low)", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "zz", "description": "Center current line in window view", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "zt", "description": "Position current line at top of window", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "zb", "description": "Position current line at bottom of window", "category": "Motion & Navigation", "context": "Normal"},
            {"keys": "i", "description": "Enter Insert mode before cursor", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "I", "description": "Enter Insert mode at first non-blank character", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "a", "description": "Enter Insert mode after cursor (append)", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "A", "description": "Enter Insert mode at end of line", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "o", "description": "Open new line below and enter Insert mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "O", "description": "Open new line above and enter Insert mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "v", "description": "Enter character-wise Visual mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "V", "description": "Enter line-wise Visual mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "Ctrl+V", "description": "Enter block-wise Visual mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "Esc", "description": "Return to Normal mode / cancel pending command", "category": "Mode Transitions"},
            {"keys": "Ctrl+[", "description": "Alternative escape to Normal mode", "category": "Mode Transitions"},
            {"keys": "x", "description": "Delete character under cursor", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "X", "description": "Delete character before cursor", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "dw", "description": "Delete from cursor to start of next word", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "diw", "description": "Delete inner word under cursor", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "daw", "description": "Delete word and surrounding whitespace", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "dd", "description": "Delete entire line (cut into register)", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "D", "description": "Delete from cursor to end of line", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "ciw", "description": "Change inner word under cursor", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "caw", "description": "Change word including surrounding space", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "cc", "description": "Change entire line and enter Insert mode", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "C", "description": "Change from cursor to end of line", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "r", "description": "Replace single character under cursor", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "R", "description": "Enter Replace mode", "category": "Mode Transitions", "context": "Normal"},
            {"keys": "s", "description": "Substitute character and enter Insert mode", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "S", "description": "Substitute entire line and enter Insert mode", "category": "Editing & Deletion", "context": "Normal"},
            {"keys": "yy", "description": "Yank (copy) entire current line", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "y$", "description": "Yank from cursor to end of line", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "yiw", "description": "Yank inner word under cursor", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "p", "description": "Paste register content after cursor / below line", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "P", "description": "Paste register content before cursor / above line", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "\"+y", "description": "Yank selection to system clipboard", "category": "Registers & Clipboard", "context": "Visual"},
            {"keys": "\"+p", "description": "Paste from system clipboard", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "\"_d", "description": "Delete into black-hole register (no clipboard overwrite)", "category": "Registers & Clipboard", "context": "Normal"},
            {"keys": "u", "description": "Undo last change", "category": "History & Macros", "context": "Normal"},
            {"keys": "Ctrl+R", "description": "Redo previously undone change", "category": "History & Macros", "context": "Normal"},
            {"keys": ".", "description": "Repeat last editing action", "category": "History & Macros", "context": "Normal"},
            {"keys": "q<reg>", "description": "Start recording macro into register <reg>", "category": "History & Macros", "context": "Normal"},
            {"keys": "q", "description": "Stop recording active macro", "category": "History & Macros", "context": "Normal"},
            {"keys": "@<reg>", "description": "Execute macro stored in register <reg>", "category": "History & Macros", "context": "Normal"},
            {"keys": "@@", "description": "Repeat last executed macro", "category": "History & Macros", "context": "Normal"},
            {"keys": "/", "description": "Search forward in buffer", "category": "Search & Replace", "context": "Normal"},
            {"keys": "?", "description": "Search backward in buffer", "category": "Search & Replace", "context": "Normal"},
            {"keys": "n", "description": "Jump to next search occurrence", "category": "Search & Replace", "context": "Normal"},
            {"keys": "N", "description": "Jump to previous search occurrence", "category": "Search & Replace", "context": "Normal"},
            {"keys": "*", "description": "Search forward for exact word under cursor", "category": "Search & Replace", "context": "Normal"},
            {"keys": "#", "description": "Search backward for exact word under cursor", "category": "Search & Replace", "context": "Normal"},
            {"keys": ":%s/foo/bar/g", "description": "Substitute all occurrences of foo with bar in file", "category": "Search & Replace", "context": "Command"},
            {"keys": ":%s/foo/bar/gc", "description": "Substitute with confirmation prompt for each match", "category": "Search & Replace", "context": "Command"},
            {"keys": ":nohlsearch", "description": "Clear search highlights until next search", "category": "Search & Replace", "context": "Command"},
            {"keys": ":w", "description": "Write (save) buffer to disk", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":q", "description": "Quit current window", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":q!", "description": "Force quit discarding unsaved changes", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":wq", "description": "Save file and quit", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":e <file>", "description": "Edit file in new buffer", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":bnext", "description": "Switch to next active buffer", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":bprev", "description": "Switch to previous active buffer", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": ":bd", "description": "Delete / close current buffer", "category": "File & Buffer Operations", "context": "Command"},
            {"keys": "Ctrl+W s", "description": "Split window horizontally", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W v", "description": "Split window vertically", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W h", "description": "Focus window on the left", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W j", "description": "Focus window below", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W k", "description": "Focus window above", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W l", "description": "Focus window on the right", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W w", "description": "Cycle focus to next split window", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W c", "description": "Close current split window", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "Ctrl+W =", "description": "Equalize width and height of all splits", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": ":tabnew", "description": "Open new tab page", "category": "Window Splits & Tabs", "context": "Command"},
            {"keys": "gt", "description": "Switch to next tab page", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "gT", "description": "Switch to previous tab page", "category": "Window Splits & Tabs", "context": "Normal"},
            {"keys": "gd", "description": "LSP: Go to definition", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "gD", "description": "LSP: Go to declaration", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "gr", "description": "LSP: List references", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "gi", "description": "LSP: Go to implementation", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "K", "description": "LSP: Show hover documentation tooltip", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "<leader>ca", "description": "LSP: Code action prompt", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "<leader>rn", "description": "LSP: Rename symbol project-wide", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "[d", "description": "LSP: Jump to previous diagnostic", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "]d", "description": "LSP: Jump to next diagnostic", "category": "LSP & Code Intelligence", "context": "Normal"}
        ]
    },
    {
        "id": "template-lazygit",
        "name": "LazyGit",
        "icon": "merge",
        "program": "LazyGit",
        "programId": "lazygit",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "h / l", "description": "Switch left / right panel view", "category": "Panel Navigation"},
            {"keys": "j / k", "description": "Move up / down in current item list", "category": "Panel Navigation"},
            {"keys": "1", "description": "Focus Status panel", "category": "Panel Navigation"},
            {"keys": "2", "description": "Focus Files panel", "category": "Panel Navigation"},
            {"keys": "3", "description": "Focus Branches panel", "category": "Panel Navigation"},
            {"keys": "4", "description": "Focus Commits panel", "category": "Panel Navigation"},
            {"keys": "5", "description": "Focus Stash panel", "category": "Panel Navigation"},
            {"keys": "[ / ]", "description": "Switch tabs in current panel", "category": "Panel Navigation"},
            {"keys": "Space", "description": "Stage / unstage selected file or hunk", "category": "Staging & Commits"},
            {"keys": "a", "description": "Stage / unstage all modified files", "category": "Staging & Commits"},
            {"keys": "c", "description": "Commit staged changes with message prompt", "category": "Staging & Commits"},
            {"keys": "C", "description": "Commit staged changes with external editor", "category": "Staging & Commits"},
            {"keys": "A", "description": "Amend last commit with staged changes", "category": "Staging & Commits"},
            {"keys": "d", "description": "Discard changes in selected file / hunk", "category": "Staging & Commits"},
            {"keys": "e", "description": "Open selected file in editor", "category": "File Operations"},
            {"keys": "o", "description": "Open file in default system application", "category": "File Operations"},
            {"keys": "i", "description": "Add selected file to .gitignore", "category": "File Operations"},
            {"keys": "p", "description": "Git pull from remote repository", "category": "Remotes & Sync"},
            {"keys": "P", "description": "Git push to upstream branch", "category": "Remotes & Sync"},
            {"keys": "f", "description": "Git fetch from all remotes", "category": "Remotes & Sync"},
            {"keys": "Space", "description": "Checkout selected branch", "category": "Branches & Merging", "context": "Branches"},
            {"keys": "n", "description": "Create new branch from current HEAD", "category": "Branches & Merging"},
            {"keys": "M", "description": "Merge selected branch into current branch", "category": "Branches & Merging"},
            {"keys": "r", "description": "Rebase current branch onto selected branch", "category": "Branches & Merging"},
            {"keys": "F", "description": "Fast-forward branch from upstream", "category": "Branches & Merging"},
            {"keys": "s", "description": "Stash current uncommitted changes", "category": "Stash"},
            {"keys": "g", "description": "View interactive reset / rebase options", "category": "Commits & History"},
            {"keys": "s", "description": "Squash commit into parent commit", "category": "Commits & History", "context": "Commits"},
            {"keys": "t", "description": "Revert selected commit", "category": "Commits & History", "context": "Commits"},
            {"keys": "Enter", "description": "View commit details / diff drill-down", "category": "Commits & History"},
            {"keys": "/", "description": "Search items in focused panel", "category": "General"},
            {"keys": "?", "description": "Show interactive keybindings cheat sheet", "category": "General"},
            {"keys": "<", "description": "Scroll diff preview left / up", "category": "Diff Preview"},
            {"keys": ">", "description": "Scroll diff preview right / down", "category": "Diff Preview"},
            {"keys": "q", "description": "Quit LazyGit", "category": "General"}
        ]
    },
    {
        "id": "template-tmux",
        "name": "Tmux",
        "icon": "terminal",
        "program": "Tmux",
        "programId": "tmux",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+B c", "description": "Create new tmux window", "category": "Window Management"},
            {"keys": "Ctrl+B ,", "description": "Rename active window", "category": "Window Management"},
            {"keys": "Ctrl+B &", "description": "Kill / close active window", "category": "Window Management"},
            {"keys": "Ctrl+B n", "description": "Switch to next window", "category": "Window Management"},
            {"keys": "Ctrl+B p", "description": "Switch to previous window", "category": "Window Management"},
            {"keys": "Ctrl+B <0-9>", "description": "Switch to window by index number", "category": "Window Management"},
            {"keys": "Ctrl+B w", "description": "Interactive window / session list chooser", "category": "Window Management"},
            {"keys": "Ctrl+B \"", "description": "Split active pane horizontally (top/bottom)", "category": "Pane Management"},
            {"keys": "Ctrl+B %", "description": "Split active pane vertically (left/right)", "category": "Pane Management"},
            {"keys": "Ctrl+B o", "description": "Cycle focus to next pane", "category": "Pane Management"},
            {"keys": "Ctrl+B ;", "description": "Switch to previously focused pane", "category": "Pane Management"},
            {"keys": "Ctrl+B Arrow", "description": "Move focus to pane in specified direction", "category": "Pane Management"},
            {"keys": "Ctrl+B x", "description": "Kill / close active pane", "category": "Pane Management"},
            {"keys": "Ctrl+B z", "description": "Toggle zoom / fullscreen for active pane", "category": "Pane Management"},
            {"keys": "Ctrl+B {", "description": "Swap active pane with previous pane", "category": "Pane Management"},
            {"keys": "Ctrl+B }", "description": "Swap active pane with next pane", "category": "Pane Management"},
            {"keys": "Ctrl+B !", "description": "Break active pane out into a new window", "category": "Pane Management"},
            {"keys": "Ctrl+B Space", "description": "Cycle through preset pane layouts", "category": "Pane Management"},
            {"keys": "Ctrl+B Ctrl+Arrow", "description": "Resize active pane by 1 cell in direction", "category": "Pane Resizing"},
            {"keys": "Ctrl+B Alt+Arrow", "description": "Resize active pane by 5 cells in direction", "category": "Pane Resizing"},
            {"keys": "Ctrl+B [", "description": "Enter scrollback / Copy mode", "category": "Copy Mode & Scrollback"},
            {"keys": "Space", "description": "Start text selection in vi copy mode", "category": "Copy Mode & Scrollback", "context": "Copy Mode"},
            {"keys": "Enter", "description": "Copy selection and exit copy mode", "category": "Copy Mode & Scrollback", "context": "Copy Mode"},
            {"keys": "Ctrl+B ]", "description": "Paste most recently copied buffer", "category": "Copy Mode & Scrollback"},
            {"keys": "Ctrl+B #", "description": "List all clipboard paste buffers", "category": "Copy Mode & Scrollback"},
            {"keys": "Ctrl+B d", "description": "Detach current client from session", "category": "Session Management"},
            {"keys": "Ctrl+B s", "description": "Interactive session list selector", "category": "Session Management"},
            {"keys": "Ctrl+B $", "description": "Rename current session", "category": "Session Management"},
            {"keys": "Ctrl+B (", "description": "Switch to previous attached session", "category": "Session Management"},
            {"keys": "Ctrl+B )", "description": "Switch to next attached session", "category": "Session Management"},
            {"keys": "Ctrl+B :", "description": "Open tmux command prompt", "category": "General"},
            {"keys": "Ctrl+B ?", "description": "Show complete list of all keybindings", "category": "General"},
            {"keys": "Ctrl+B t", "description": "Show big digital clock in pane", "category": "General"}
        ]
    },
    {
        "id": "template-zellij",
        "name": "Zellij",
        "icon": "view_quilt",
        "program": "Zellij",
        "programId": "zellij",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+P", "description": "Enter Pane mode", "category": "Mode Switching"},
            {"keys": "Ctrl+T", "description": "Enter Tab mode", "category": "Mode Switching"},
            {"keys": "Ctrl+N", "description": "Enter Resize mode", "category": "Mode Switching"},
            {"keys": "Ctrl+S", "description": "Enter Scroll / Search mode", "category": "Mode Switching"},
            {"keys": "Ctrl+O", "description": "Enter Session mode", "category": "Mode Switching"},
            {"keys": "Ctrl+G", "description": "Lock / unlock interface inputs", "category": "Mode Switching"},
            {"keys": "Esc", "description": "Return to Normal mode", "category": "Mode Switching"},
            {"keys": "Ctrl+P n", "description": "New pane in automatic direction", "category": "Panes"},
            {"keys": "Ctrl+P d", "description": "New pane split downwards", "category": "Panes"},
            {"keys": "Ctrl+P r", "description": "New pane split to the right", "category": "Panes"},
            {"keys": "Ctrl+P x", "description": "Close active pane", "category": "Panes"},
            {"keys": "Ctrl+P f", "description": "Toggle floating / tiled pane state", "category": "Panes"},
            {"keys": "Ctrl+P z", "description": "Toggle fullscreen zoom for active pane", "category": "Panes"},
            {"keys": "Ctrl+P e", "description": "Toggle pane embedded / floating frame", "category": "Panes"},
            {"keys": "Ctrl+P Arrow", "description": "Move focus between panes", "category": "Panes"},
            {"keys": "Alt+Arrow", "description": "Quick move focus in direction", "category": "Panes"},
            {"keys": "Alt+[ / Alt+]", "description": "Previous / next active tab", "category": "Tabs"},
            {"keys": "Ctrl+T n", "description": "Create new tab", "category": "Tabs"},
            {"keys": "Ctrl+T x", "description": "Close active tab", "category": "Tabs"},
            {"keys": "Ctrl+T r", "description": "Rename active tab", "category": "Tabs"},
            {"keys": "Ctrl+T <1-9>", "description": "Jump to tab by number", "category": "Tabs"},
            {"keys": "Ctrl+S s", "description": "Search text in scrollback history", "category": "Scroll & Search"},
            {"keys": "Ctrl+S e", "description": "Open scrollback in external editor", "category": "Scroll & Search"},
            {"keys": "Ctrl+O d", "description": "Detach from current session", "category": "Sessions"},
            {"keys": "Ctrl+O w", "description": "Open session manager UI", "category": "Sessions"},
            {"keys": "Ctrl+Q", "description": "Quit Zellij", "category": "General"}
        ]
    },
    {
        "id": "template-yazi",
        "name": "Yazi",
        "icon": "folder",
        "program": "Yazi",
        "programId": "yazi",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "h", "description": "Leave directory / jump to parent", "category": "Navigation"},
            {"keys": "j", "description": "Move cursor down in file list", "category": "Navigation"},
            {"keys": "k", "description": "Move cursor up in file list", "category": "Navigation"},
            {"keys": "l", "description": "Enter directory or open file", "category": "Navigation"},
            {"keys": "g g", "description": "Jump to first entry in folder", "category": "Navigation"},
            {"keys": "G", "description": "Jump to last entry in folder", "category": "Navigation"},
            {"keys": "Ctrl+U", "description": "Scroll half page up", "category": "Navigation"},
            {"keys": "Ctrl+D", "description": "Scroll half page down", "category": "Navigation"},
            {"keys": "Space", "description": "Toggle selection of current file / directory", "category": "Selection"},
            {"keys": "v", "description": "Enter visual selection mode", "category": "Selection"},
            {"keys": "V", "description": "Enter visual unset selection mode", "category": "Selection"},
            {"keys": "Ctrl+A", "description": "Select all files in current folder", "category": "Selection"},
            {"keys": "Ctrl+R", "description": "Inverse selection state of all files", "category": "Selection"},
            {"keys": "y", "description": "Yank (copy) selected files to internal clipboard", "category": "File Operations"},
            {"keys": "x", "description": "Cut selected files for moving", "category": "File Operations"},
            {"keys": "p", "description": "Paste copied / cut files here", "category": "File Operations"},
            {"keys": "P", "description": "Paste symlink to copied files", "category": "File Operations"},
            {"keys": "d", "description": "Move selected files to Trash", "category": "File Operations"},
            {"keys": "D", "description": "Permanently delete selected files", "category": "File Operations"},
            {"keys": "a", "description": "Create new file (append / for directory)", "category": "File Operations"},
            {"keys": "r", "description": "Rename selected file", "category": "File Operations"},
            {"keys": "R", "description": "Batch rename selected files in external editor", "category": "File Operations"},
            {"keys": "z", "description": "Jump to directory via zoxide interactive search", "category": "Find & Filter"},
            {"keys": "/", "description": "Find file by filter in current directory", "category": "Find & Filter"},
            {"keys": "f", "description": "Filter files interactively (type-ahead)", "category": "Find & Filter"},
            {"keys": "s", "description": "Search file contents with ripgrep", "category": "Find & Filter"},
            {"keys": "t", "description": "Create new file manager tab", "category": "Tabs"},
            {"keys": "1-9", "description": "Switch to tab by index", "category": "Tabs"},
            {"keys": "[ / ]", "description": "Switch to previous / next tab", "category": "Tabs"},
            {"keys": "w", "description": "Open task manager panel", "category": "Tasks & Plugins"},
            {"keys": ":", "description": "Open command line input prompt", "category": "General"},
            {"keys": "~", "description": "Open help menu overlay", "category": "General"},
            {"keys": "q", "description": "Quit Yazi", "category": "General"}
        ]
    },
    {
        "id": "template-ranger",
        "name": "Ranger",
        "icon": "folder_copy",
        "program": "Ranger",
        "programId": "ranger",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "h", "description": "Parent directory", "category": "Navigation"},
            {"keys": "j", "description": "Move down in list", "category": "Navigation"},
            {"keys": "k", "description": "Move up in list", "category": "Navigation"},
            {"keys": "l", "description": "Open file / enter directory", "category": "Navigation"},
            {"keys": "gg", "description": "Jump to top of directory", "category": "Navigation"},
            {"keys": "G", "description": "Jump to bottom of directory", "category": "Navigation"},
            {"keys": "Space", "description": "Toggle selection of current file", "category": "Selection"},
            {"keys": "v", "description": "Invert all selections in folder", "category": "Selection"},
            {"keys": "V", "description": "Enter visual selection mode", "category": "Selection"},
            {"keys": "yy", "description": "Copy (yank) selected files", "category": "File Operations"},
            {"keys": "dd", "description": "Cut selected files", "category": "File Operations"},
            {"keys": "pp", "description": "Paste copied / cut files", "category": "File Operations"},
            {"keys": "dD", "description": "Delete selected files permanently", "category": "File Operations"},
            {"keys": "cw", "description": "Rename current file", "category": "File Operations"},
            {"keys": "zh", "description": "Toggle display of hidden files", "category": "Display"},
            {"keys": "zp", "description": "Toggle file preview pane", "category": "Display"},
            {"keys": "f", "description": "Quick jump / find file", "category": "Find"},
            {"keys": "/", "description": "Search forward in current folder", "category": "Find"},
            {"keys": "n", "description": "Next search match", "category": "Find"},
            {"keys": "N", "description": "Previous search match", "category": "Find"},
            {"keys": "gn", "description": "Open new tab", "category": "Tabs"},
            {"keys": "gc", "description": "Close current tab", "category": "Tabs"},
            {"keys": "Tab", "description": "Switch to next tab", "category": "Tabs"},
            {"keys": "Shift+Tab", "description": "Switch to previous tab", "category": "Tabs"},
            {"keys": ":", "description": "Open console command line", "category": "General"},
            {"keys": "q", "description": "Quit Ranger", "category": "General"}
        ]
    },
    {
        "id": "template-kitty",
        "name": "Kitty Terminal",
        "icon": "terminal",
        "program": "Kitty",
        "programId": "kitty",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+Shift+Enter", "description": "New window split in current tab", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+W", "description": "Close active window split", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+]", "description": "Focus next window in layout", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+[", "description": "Focus previous window in layout", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+F", "description": "Move active window forward", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+B", "description": "Move active window backward", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+L", "description": "Cycle through window layouts (splits, stack, grid)", "category": "Windows & Splits"},
            {"keys": "Ctrl+Shift+T", "description": "Create new tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+Q", "description": "Close active tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+Right", "description": "Switch to next tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+Left", "description": "Switch to previous tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+Alt+T", "description": "Set active tab title", "category": "Tabs"},
            {"keys": "Ctrl+Shift+C", "description": "Copy selection to system clipboard", "category": "Clipboard & Selection"},
            {"keys": "Ctrl+Shift+V", "description": "Paste from system clipboard", "category": "Clipboard & Selection"},
            {"keys": "Ctrl+Shift+S", "description": "Paste from primary selection", "category": "Clipboard & Selection"},
            {"keys": "Ctrl+Shift+O", "description": "Pass selection to external program", "category": "Clipboard & Selection"},
            {"keys": "Ctrl+Shift+Page_Up", "description": "Scroll terminal history one page up", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+Page_Down", "description": "Scroll terminal history one page down", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+Home", "description": "Scroll to top of terminal history", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+End", "description": "Scroll to bottom of terminal output", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+H", "description": "View entire scrollback in pager / editor", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+G", "description": "View last shell command output in pager", "category": "Scrollback & History"},
            {"keys": "Ctrl+Shift+Equal", "description": "Increase font size", "category": "Appearance & Font"},
            {"keys": "Ctrl+Shift+Minus", "description": "Decrease font size", "category": "Appearance & Font"},
            {"keys": "Ctrl+Shift+BackSpace", "description": "Reset font size to default", "category": "Appearance & Font"},
            {"keys": "Ctrl+Shift+E", "description": "Open URL / hyperlinks hint mode", "category": "Hints & URL"},
            {"keys": "Ctrl+Shift+P > F", "description": "Insert path hint under cursor", "category": "Hints & URL"},
            {"keys": "Ctrl+Shift+F11", "description": "Toggle fullscreen window state", "category": "General"},
            {"keys": "Ctrl+Shift+F5", "description": "Reload kitty configuration file", "category": "General"},
            {"keys": "Ctrl+Shift+F6", "description": "Debug kitty configuration & OpenGL info", "category": "General"}
        ]
    },
    {
        "id": "template-ghostty",
        "name": "Ghostty",
        "icon": "terminal",
        "program": "Ghostty",
        "programId": "ghostty",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+Shift+D", "description": "Split pane horizontally", "category": "Splits"},
            {"keys": "Ctrl+Shift+E", "description": "Split pane vertically", "category": "Splits"},
            {"keys": "Ctrl+Shift+W", "description": "Close active split pane", "category": "Splits"},
            {"keys": "Ctrl+Shift+O", "description": "Toggle zoom on focused split pane", "category": "Splits"},
            {"keys": "Ctrl+Shift+H / J / K / L", "description": "Navigate focus between split panes", "category": "Splits"},
            {"keys": "Ctrl+Shift+T", "description": "Open new tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+Tab", "description": "Switch to previous tab", "category": "Tabs"},
            {"keys": "Ctrl+Tab", "description": "Switch to next tab", "category": "Tabs"},
            {"keys": "Ctrl+Shift+C", "description": "Copy selection to clipboard", "category": "Clipboard"},
            {"keys": "Ctrl+Shift+V", "description": "Paste from clipboard", "category": "Clipboard"},
            {"keys": "Ctrl+Equal", "description": "Increase font size", "category": "Font"},
            {"keys": "Ctrl+Minus", "description": "Decrease font size", "category": "Font"},
            {"keys": "Ctrl+0", "description": "Reset font size to default", "category": "Font"},
            {"keys": "Ctrl+Shift+Comma", "description": "Open configuration file in editor", "category": "General"},
            {"keys": "Ctrl+Shift+I", "description": "Open terminal inspector & debug overlay", "category": "General"}
        ]
    },
    {
        "id": "template-btop",
        "name": "Btop / Htop",
        "icon": "speed",
        "program": "Btop",
        "programId": "btop",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Up / Down", "description": "Select process in list", "category": "Process Navigation"},
            {"keys": "j / k", "description": "Move cursor down / up (vi keys)", "category": "Process Navigation"},
            {"keys": "Page_Up / Page_Down", "description": "Jump one full page up / down", "category": "Process Navigation"},
            {"keys": "Home / End", "description": "Jump to top / bottom of process list", "category": "Process Navigation"},
            {"keys": "Enter", "description": "Show detailed process inspection box", "category": "Process Details"},
            {"keys": "f", "description": "Filter processes by name / command", "category": "Filtering & Sorting"},
            {"keys": "e", "description": "Toggle process tree view / flat list", "category": "Filtering & Sorting"},
            {"keys": "r", "description": "Reverse sort order (descending / ascending)", "category": "Filtering & Sorting"},
            {"keys": "m", "description": "Sort by Memory usage", "category": "Filtering & Sorting"},
            {"keys": "c", "description": "Sort by CPU usage", "category": "Filtering & Sorting"},
            {"keys": "p", "description": "Sort by Process ID (PID)", "category": "Filtering & Sorting"},
            {"keys": "n", "description": "Sort by Process Name", "category": "Filtering & Sorting"},
            {"keys": "k", "description": "Send SIGKILL (kill) to selected process", "category": "Signals & Actions"},
            {"keys": "t", "description": "Send SIGTERM (terminate) to selected process", "category": "Signals & Actions"},
            {"keys": "i", "description": "Send SIGINT (interrupt) to selected process", "category": "Signals & Actions"},
            {"keys": "1", "description": "Toggle CPU widget box display", "category": "Panels & Views"},
            {"keys": "2", "description": "Toggle Memory widget box display", "category": "Panels & Views"},
            {"keys": "3", "description": "Toggle Disks widget box display", "category": "Panels & Views"},
            {"keys": "4", "description": "Toggle Network widget box display", "category": "Panels & Views"},
            {"keys": "5", "description": "Toggle Processes box display", "category": "Panels & Views"},
            {"keys": "h", "description": "Open help and keybindings overlay", "category": "General"},
            {"keys": "o", "description": "Open settings & theme configurator", "category": "General"},
            {"keys": "q / Esc", "description": "Quit btop", "category": "General"}
        ]
    },
    {
        "id": "template-helix",
        "name": "Helix Editor",
        "icon": "terminal",
        "program": "Helix",
        "programId": "hx",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "h / j / k / l", "description": "Move cursor left / down / up / right", "category": "Movement", "context": "Normal"},
            {"keys": "w / b / e", "description": "Move next / previous word start / end", "category": "Movement", "context": "Normal"},
            {"keys": "x", "description": "Select current line (expand selection downwards)", "category": "Selection", "context": "Normal"},
            {"keys": "X", "description": "Extend selection to line above", "category": "Selection", "context": "Normal"},
            {"keys": "d", "description": "Delete selection into clipboard", "category": "Editing", "context": "Normal"},
            {"keys": "c", "description": "Change selection (delete & enter Insert mode)", "category": "Editing", "context": "Normal"},
            {"keys": "y", "description": "Yank selection to clipboard", "category": "Editing", "context": "Normal"},
            {"keys": "p", "description": "Paste clipboard content after selection", "category": "Editing", "context": "Normal"},
            {"keys": "P", "description": "Paste clipboard content before selection", "category": "Editing", "context": "Normal"},
            {"keys": "u", "description": "Undo last change", "category": "History", "context": "Normal"},
            {"keys": "U", "description": "Redo undone change", "category": "History", "context": "Normal"},
            {"keys": "i", "description": "Insert before selection", "category": "Insert Mode", "context": "Normal"},
            {"keys": "a", "description": "Append after selection", "category": "Insert Mode", "context": "Normal"},
            {"keys": "o", "description": "Open new line below and insert", "category": "Insert Mode", "context": "Normal"},
            {"keys": "O", "description": "Open new line above and insert", "category": "Insert Mode", "context": "Normal"},
            {"keys": "s", "description": "Select / split sub-matches using regex", "category": "Multi-Cursor", "context": "Normal"},
            {"keys": "C", "description": "Add cursor on next line matching current column", "category": "Multi-Cursor", "context": "Normal"},
            {"keys": "Alt+C", "description": "Add cursor on previous line", "category": "Multi-Cursor", "context": "Normal"},
            {"keys": ", (comma)", "description": "Clear all secondary selections / cursors", "category": "Multi-Cursor", "context": "Normal"},
            {"keys": "Space f", "description": "File picker (fuzzy find)", "category": "Pickers & Navigation", "context": "Normal"},
            {"keys": "Space b", "description": "Buffer picker", "category": "Pickers & Navigation", "context": "Normal"},
            {"keys": "Space /", "description": "Global project text search", "category": "Pickers & Navigation", "context": "Normal"},
            {"keys": "gd", "description": "Go to definition (LSP)", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "gr", "description": "Go to references (LSP)", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "Space a", "description": "Code action prompt (LSP)", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "Space r", "description": "Rename symbol (LSP)", "category": "LSP & Code Intelligence", "context": "Normal"},
            {"keys": "Ctrl+W v", "description": "Split view vertically", "category": "Splits & Windows", "context": "Normal"},
            {"keys": "Ctrl+W s", "description": "Split view horizontally", "category": "Splits & Windows", "context": "Normal"},
            {"keys": "Ctrl+W h/j/k/l", "description": "Navigate between split views", "category": "Splits & Windows", "context": "Normal"},
            {"keys": ":w", "description": "Write / save file", "category": "Commands", "context": "Command"},
            {"keys": ":q", "description": "Quit Helix", "category": "Commands", "context": "Command"}
        ]
    },
    {
        "id": "template-zed",
        "name": "Zed",
        "icon": "code",
        "program": "Zed",
        "programId": "zed",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+Shift+P", "description": "Open command palette", "category": "General"},
            {"keys": "Ctrl+P", "description": "Quick open file picker", "category": "Navigation"},
            {"keys": "Ctrl+,", "description": "Open settings", "category": "General"},
            {"keys": "Ctrl+B", "description": "Toggle left project panel", "category": "Panels & View"},
            {"keys": "Ctrl+R", "description": "Toggle right assistant / chat panel", "category": "Panels & View"},
            {"keys": "Ctrl+J", "description": "Toggle bottom terminal panel", "category": "Terminal"},
            {"keys": "Ctrl+`", "description": "Toggle terminal dock", "category": "Terminal"},
            {"keys": "Ctrl+S", "description": "Save current file", "category": "File Management"},
            {"keys": "Ctrl+W", "description": "Close current tab", "category": "File Management"},
            {"keys": "Ctrl+Shift+T", "description": "Reopen last closed tab", "category": "File Management"},
            {"keys": "Ctrl+Tab", "description": "Switch to next tab", "category": "Navigation"},
            {"keys": "Ctrl+Shift+Tab", "description": "Switch to previous tab", "category": "Navigation"},
            {"keys": "Ctrl+K Ctrl+Right", "description": "Split pane to right", "category": "Panes"},
            {"keys": "Ctrl+K Ctrl+Down", "description": "Split pane downwards", "category": "Panes"},
            {"keys": "Ctrl+D", "description": "Select next occurrence of word", "category": "Editing"},
            {"keys": "Ctrl+Shift+L", "description": "Select all occurrences of word", "category": "Editing"},
            {"keys": "Alt+Up / Alt+Down", "description": "Move line up / down", "category": "Editing"},
            {"keys": "Shift+Alt+Up / Down", "description": "Duplicate line up / down", "category": "Editing"},
            {"keys": "Ctrl+/", "description": "Toggle line comment", "category": "Editing"},
            {"keys": "F12", "description": "Go to definition (LSP)", "category": "LSP & Refactoring"},
            {"keys": "Shift+F12", "description": "Find references (LSP)", "category": "LSP & Refactoring"},
            {"keys": "F2", "description": "Rename symbol (LSP)", "category": "LSP & Refactoring"},
            {"keys": "Ctrl+.", "description": "Code actions / quick fixes", "category": "LSP & Refactoring"},
            {"keys": "Shift+Alt+F", "description": "Format buffer", "category": "LSP & Refactoring"},
            {"keys": "Ctrl+Shift+F", "description": "Project-wide search", "category": "Search"}
        ]
    },
    {
        "id": "template-intellij",
        "name": "IntelliJ IDEA",
        "icon": "integration_instructions",
        "program": "IntelliJ IDEA",
        "programId": "idea",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Shift Shift", "description": "Search everywhere (classes, files, actions)", "category": "Search & Navigation"},
            {"keys": "Ctrl+Shift+A", "description": "Find and run IDE action", "category": "Search & Navigation"},
            {"keys": "Ctrl+N", "description": "Go to Class", "category": "Search & Navigation"},
            {"keys": "Ctrl+Shift+N", "description": "Go to File", "category": "Search & Navigation"},
            {"keys": "Ctrl+Alt+Shift+N", "description": "Go to Symbol", "category": "Search & Navigation"},
            {"keys": "Ctrl+E", "description": "Recent files popup", "category": "Search & Navigation"},
            {"keys": "Ctrl+Shift+E", "description": "Recently edited locations", "category": "Search & Navigation"},
            {"keys": "Ctrl+B / Ctrl+LeftClick", "description": "Go to declaration / definition", "category": "Search & Navigation"},
            {"keys": "Ctrl+Alt+B", "description": "Go to implementation(s)", "category": "Search & Navigation"},
            {"keys": "Ctrl+Shift+I", "description": "Open quick definition lookup popup", "category": "Search & Navigation"},
            {"keys": "Ctrl+U", "description": "Go to super-method / super-class", "category": "Search & Navigation"},
            {"keys": "Alt+F7", "description": "Find usages project-wide", "category": "Search & Navigation"},
            {"keys": "Ctrl+F12", "description": "File structure / outline popup", "category": "Search & Navigation"},
            {"keys": "Ctrl+H", "description": "Type hierarchy tree", "category": "Search & Navigation"},
            {"keys": "Ctrl+G", "description": "Go to line / column number", "category": "Search & Navigation"},
            {"keys": "Ctrl+F", "description": "Find in current file", "category": "Find & Replace"},
            {"keys": "Ctrl+R", "description": "Replace in current file", "category": "Find & Replace"},
            {"keys": "Ctrl+Shift+F", "description": "Find text across entire project", "category": "Find & Replace"},
            {"keys": "Ctrl+Shift+R", "description": "Replace text across entire project", "category": "Find & Replace"},
            {"keys": "Ctrl+Space", "description": "Basic code completion", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Shift+Space", "description": "Smart type-aware code completion", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+P", "description": "Show parameter information tooltip", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Q", "description": "Quick documentation popup", "category": "Editing & Code Completion"},
            {"keys": "Alt+Insert", "description": "Generate code (constructors, getters, tests)", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+O", "description": "Override base class methods", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+I", "description": "Implement interface methods", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Alt+T", "description": "Surround selection with (if, try/catch, while)", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+/", "description": "Toggle line comment", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Shift+/", "description": "Toggle block comment", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+W", "description": "Incrementally expand syntactic selection", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Shift+W", "description": "Shrink syntactic selection", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+D", "description": "Duplicate line or selection", "category": "Editing & Code Completion"},
            {"keys": "Ctrl+Y", "description": "Delete current line", "category": "Editing & Code Completion"},
            {"keys": "Shift+Alt+Up / Down", "description": "Move line up / down", "category": "Editing & Code Completion"},
            {"keys": "Shift+F6", "description": "Rename symbol refactoring", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+V", "description": "Extract variable from expression", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+M", "description": "Extract method from selection", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+C", "description": "Extract constant", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+P", "description": "Extract parameter", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+N", "description": "Inline variable or method", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+L", "description": "Reformat code according to code style", "category": "Refactoring"},
            {"keys": "Ctrl+Alt+O", "description": "Optimize and clean up imports", "category": "Refactoring"},
            {"keys": "Alt+Enter", "description": "Show intention actions and quick fixes", "category": "Refactoring"},
            {"keys": "Shift+F10", "description": "Run current configuration", "category": "Run & Debug"},
            {"keys": "Shift+F9", "description": "Debug current configuration", "category": "Run & Debug"},
            {"keys": "Ctrl+F2", "description": "Stop running process", "category": "Run & Debug"},
            {"keys": "Ctrl+F8", "description": "Toggle line breakpoint", "category": "Run & Debug"},
            {"keys": "F8", "description": "Step over during debug", "category": "Run & Debug"},
            {"keys": "F7", "description": "Step into during debug", "category": "Run & Debug"},
            {"keys": "Shift+F8", "description": "Step out of function", "category": "Run & Debug"},
            {"keys": "Alt+F9", "description": "Run to cursor position", "category": "Run & Debug"},
            {"keys": "Alt+F8", "description": "Evaluate expression popup", "category": "Run & Debug"},
            {"keys": "Alt+1", "description": "Toggle Project tool window", "category": "Tool Windows"},
            {"keys": "Alt+7", "description": "Toggle Structure tool window", "category": "Tool Windows"},
            {"keys": "Alt+9", "description": "Toggle Git tool window", "category": "Tool Windows"},
            {"keys": "Alt+F12", "description": "Toggle integrated Terminal", "category": "Tool Windows"},
            {"keys": "Ctrl+K", "description": "Commit changes dialog", "category": "Version Control"},
            {"keys": "Ctrl+Shift+K", "description": "Push commits to remote", "category": "Version Control"},
            {"keys": "Ctrl+T", "description": "Update project (git pull)", "category": "Version Control"}
        ]
    },
    {
        "id": "template-browsers",
        "name": "Web Browsers",
        "icon": "public",
        "program": "Firefox / Chrome",
        "programId": "firefox",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+T", "description": "Open new browser tab", "category": "Tab Management"},
            {"keys": "Ctrl+W", "description": "Close active tab", "category": "Tab Management"},
            {"keys": "Ctrl+Shift+T", "description": "Reopen last closed tab", "category": "Tab Management"},
            {"keys": "Ctrl+Tab", "description": "Switch to next tab on the right", "category": "Tab Management"},
            {"keys": "Ctrl+Shift+Tab", "description": "Switch to previous tab on the left", "category": "Tab Management"},
            {"keys": "Ctrl+1 to 8", "description": "Jump to tab 1 through 8", "category": "Tab Management"},
            {"keys": "Ctrl+9", "description": "Jump to the rightmost tab", "category": "Tab Management"},
            {"keys": "Ctrl+N", "description": "Open new browser window", "category": "Window Management"},
            {"keys": "Ctrl+Shift+N", "description": "Open new Incognito / Private window", "category": "Window Management"},
            {"keys": "Ctrl+Shift+W", "description": "Close entire browser window", "category": "Window Management"},
            {"keys": "Ctrl+L / Alt+D", "description": "Focus and select URL address bar", "category": "Navigation"},
            {"keys": "Ctrl+K", "description": "Focus address bar in search mode", "category": "Navigation"},
            {"keys": "F5 / Ctrl+R", "description": "Reload current page", "category": "Navigation"},
            {"keys": "Ctrl+F5 / Ctrl+Shift+R", "description": "Hard reload bypassing local cache", "category": "Navigation"},
            {"keys": "Alt+Left / BackSpace", "description": "Go back in browsing history", "category": "Navigation"},
            {"keys": "Alt+Right / Shift+BackSpace", "description": "Go forward in browsing history", "category": "Navigation"},
            {"keys": "Alt+Home", "description": "Navigate to home page", "category": "Navigation"},
            {"keys": "Ctrl+F", "description": "Find text in page", "category": "Page Actions"},
            {"keys": "Ctrl+G / F3", "description": "Find next match in page", "category": "Page Actions"},
            {"keys": "Ctrl+Shift+G / Shift+F3", "description": "Find previous match in page", "category": "Page Actions"},
            {"keys": "Ctrl+D", "description": "Bookmark current web page", "category": "Bookmarks & History"},
            {"keys": "Ctrl+Shift+O / Ctrl+Shift+B", "description": "Open bookmarks manager", "category": "Bookmarks & History"},
            {"keys": "Ctrl+H", "description": "Open browsing history sidebar / page", "category": "Bookmarks & History"},
            {"keys": "Ctrl+J", "description": "Open downloads list / manager", "category": "Downloads & Tools"},
            {"keys": "Ctrl+P", "description": "Print current web page", "category": "Page Actions"},
            {"keys": "Ctrl+S", "description": "Save current page as HTML", "category": "Page Actions"},
            {"keys": "Ctrl+Equal / Ctrl++", "description": "Zoom in page content", "category": "Page Actions"},
            {"keys": "Ctrl+Minus", "description": "Zoom out page content", "category": "Page Actions"},
            {"keys": "Ctrl+0", "description": "Reset zoom scale to 100%", "category": "Page Actions"},
            {"keys": "F11", "description": "Toggle fullscreen mode", "category": "Page Actions"},
            {"keys": "F12 / Ctrl+Shift+I", "description": "Toggle developer tools inspector", "category": "Developer Tools"},
            {"keys": "Ctrl+Shift+J / Ctrl+Shift+K", "description": "Open developer tools Console", "category": "Developer Tools"},
            {"keys": "Ctrl+Shift+C", "description": "Inspect DOM element picker", "category": "Developer Tools"},
            {"keys": "Ctrl+U", "description": "View page HTML source", "category": "Developer Tools"}
        ]
    },
    {
        "id": "template-obsidian",
        "name": "Obsidian",
        "icon": "note_alt",
        "program": "Obsidian",
        "programId": "obsidian",
        "sourceKind": "template",
        "keybinds": [
            {"keys": "Ctrl+P", "description": "Open command palette", "category": "General"},
            {"keys": "Ctrl+O", "description": "Quick switcher (find or create notes)", "category": "Navigation"},
            {"keys": "Ctrl+N", "description": "Create new note in vault", "category": "Note Management"},
            {"keys": "Ctrl+Shift+F", "description": "Search across all notes in vault", "category": "Navigation"},
            {"keys": "Ctrl+W", "description": "Close active note tab", "category": "Note Management"},
            {"keys": "Ctrl+Shift+T", "description": "Reopen last closed tab", "category": "Note Management"},
            {"keys": "Ctrl+E", "description": "Toggle between editing and reading view", "category": "View & Layout"},
            {"keys": "Ctrl+G", "description": "Open interactive graph view", "category": "View & Layout"},
            {"keys": "Ctrl+B", "description": "Toggle bold formatting on selection", "category": "Formatting"},
            {"keys": "Ctrl+I", "description": "Toggle italic formatting on selection", "category": "Formatting"},
            {"keys": "Ctrl+K", "description": "Insert Markdown link syntax", "category": "Formatting"},
            {"keys": "[[", "description": "Insert internal wikilink to another note", "category": "Formatting"},
            {"keys": "Ctrl+Enter", "description": "Toggle checklist item state (done/undone)", "category": "Formatting"},
            {"keys": "Ctrl+Shift+N", "description": "Create new canvas file", "category": "Canvas"},
            {"keys": "Ctrl+Alt+Left", "description": "Navigate back in note history", "category": "Navigation"},
            {"keys": "Ctrl+Alt+Right", "description": "Navigate forward in note history", "category": "Navigation"},
            {"keys": "Alt+D", "description": "Open daily note", "category": "Note Management"},
            {"keys": "Ctrl+,", "description": "Open Obsidian settings", "category": "General"}
        ]
    }
]

def main():
    target_path = Path("defaults/keybinds/templates.json")
    output = {
        "schemaVersion": 2,
        "templates": TEMPLATES
    }
    target_path.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    total_shortcuts = sum(len(t["keybinds"]) for t in TEMPLATES)
    print(f"Generated {len(TEMPLATES)} templates with {total_shortcuts} total shortcuts in {target_path}")

if __name__ == "__main__":
    main()
