pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.services
import qs.modules.common
import qs.modules.common.functions

/**
 * Typed, local access to the Settings index.
 *
 * The index is generated by scripts/ai/ai_settings_index.py so QML never has
 * to parse every Settings page on the hot path. This adapter owns only the
 * Settings DTO/validation
 * boundary; views and AI providers consume its small objects and never touch
 * config.json as a blob.
 */
QtObject {
    id: root

    readonly property string indexPath: FileUtils.trimFileProtocol(`${Directories.state}/user/ai/settings_index.json`)
    readonly property string generatorPath: Directories.aiSettingsIndexScriptPath
    property var index: ({ schema: 0, entries: [] })
    /** How far below the best match a result may score and still be shown. */
    readonly property real relevanceFloor: 0.5
    /** A question has a handful of answers, not a search page of them. */
    readonly property int maxResults: 6
    /**
     * The locale the index has to be built in.
     *
     * The generator used to default to a language of its own, so an English
     * interface got Portuguese labels back and the section deep-link stopped
     * matching the section titles on screen.
     */
    readonly property string language: Translation.languageCode
    property bool ready: false
    property bool rebuilding: false
    property string lastError: ""

    readonly property var entries: Array.from(root.index?.entries ?? [])

    function ensureIndex() {
        if (root.rebuilding || indexCheck.running)
            return;
        indexCheck.running = true;
    }

    function rebuild() {
        if (root.rebuilding)
            return;
        root.rebuilding = true;
        root.ready = false;
        indexBuild.running = true;
    }

    // The bytes the current index was parsed from. `watchChanges` and the
    // freshness check both reload the same file, and re-ingesting identical
    // JSON used to rebuild the scoring records for all ~2000 entries a second
    // time for no change.
    property string _ingestedRaw: ""

    function ingest(raw: string) {
        try {
            if (root.ready && raw === root._ingestedRaw)
                return;
            const parsed = JSON.parse(raw);
            if (!Array.isArray(parsed?.entries))
                throw new Error("entries are missing");
            root.index = parsed;
            root._ingestedRaw = raw;
            root.ready = true;
            root.lastError = "";
        } catch (error) {
            root._ingestedRaw = "";
            root.ready = false;
            root.lastError = String(error);
        }
    }

    function entryFor(key: string): var {
        const wanted = String(key ?? "");
        return root.entries.find(entry => String(entry?.key ?? "") === wanted) ?? null;
    }

    function currentValue(key: string): var {
        return Config.getNestedValue(Config.options, String(key).split("."));
    }

    /**
     * The full record, for the card that draws the control.
     *
     * It carries what a widget needs — type, range, options, where the page
     * is — and a few things only the index cares about.
     */
    function settingRef(entry: var, score = 0): var {
        if (!entry)
            return null;
        const ref = Object.assign({}, entry);
        ref.currentValue = root.currentValue(entry.key);
        ref.score = Number(score);
        return ref;
    }

    /**
     * The same setting, cut down to what a model can act on.
     *
     * A search used to hand back the whole index record: both languages of
     * every label, the synonym list, the byte offsets of the QML block it was
     * parsed from. That is a screenful of JSON per result, and the model read
     * it aloud — which is how an English conversation ended up quoting
     * Portuguese toggle names.
     */
    function modelRef(ref: var): var {
        if (!ref)
            return null;
        const where = [String(ref.pageName ?? ""), String(ref.sectionTitle ?? "")]
            .filter(part => part.length > 0).join(" › ");
        const projected = {
            key: String(ref.key ?? ""),
            label: String(ref.label ?? "") || String(ref.key ?? "").split(".").pop(),
            type: String(ref.type ?? ""),
            value: ref.currentValue
        };
        if (where.length > 0)
            projected.where = where;
        if (String(ref.description ?? "").length > 0)
            projected.description = String(ref.description);
        if (ref.hasUi !== true)
            projected.hasUi = false;
        return projected;
    }

    function modelRefs(refs: var): var {
        return Array.from(refs ?? []).map(ref => root.modelRef(ref)).filter(ref => ref !== null);
    }

    /** Words that name something, filler removed. Mirrors the generator. */
    readonly property var stopwords: new Set(String(`
        about and are can change configure disable do does enable find for from get
        have how i in is it its me my of on onde option options or set setting settings
        show that the their there this to turn use want was what when where which who
        why with you your
        como configurar de do dos das em como habilitar ligar desligar meu minha na no
        onde opcao opcoes para por qual que quero seu sua tem ter um uma
    `).trim().split(/\s+/))

    readonly property int stemLength: 6

    /**
     * Accent-free lowercase, so "suspensão" and "suspensao" are one word.
     */
    function normalize(value: string): string {
        return String(value ?? "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    }

    /**
     * The words in a string.
     *
     * Split on a plain character class, not on `\p{L}` — Qt's JavaScript
     * engine does not honour unicode property escapes, so that pattern matched
     * nothing and "automatic suspend" came through as a single token with a
     * space in it. Everything is accent-free by the time it gets here, so the
     * plain class loses nothing.
     */
    function tokens(value: string): var {
        return root.normalize(value)
            .split(/[^a-z0-9_]+/)
            .filter(token => token.length > 1);
    }

    /** The words of a question that actually name something. */
    function queryTokens(value: string): var {
        const all = root.tokens(value);
        const meaningful = all.filter(token => !root.stopwords.has(token));
        return meaningful.length > 0 ? meaningful : all;
    }

    function stemOf(token: string): string {
        return token.length > root.stemLength ? token.slice(0, root.stemLength) : "";
    }

    /**
     * The words of a field a stem could ever reach.
     *
     * `stemHit` only ever looks at words longer than the stem, so the short
     * ones are dropped here rather than skipped once per query token.
     */
    function stemWords(value: string): var {
        const words = String(value ?? "").split(/[^a-z0-9_]+/);
        const kept = [];
        for (let i = 0; i < words.length; i++) {
            if (words[i].length > root.stemLength)
                kept.push(words[i]);
        }
        return kept;
    }

    /** Whether any word in an already-split field starts with `stem`. */
    function stemHit(stem: string, words: var): bool {
        if (stem.length === 0)
            return false;
        for (let i = 0; i < words.length; i++) {
            if (words[i].startsWith(stem))
                return true;
        }
        return false;
    }

    /**
     * Everything scoring reads off an entry, derived once.
     *
     * Not one field below depends on the query, yet all of them used to be
     * rebuilt inside the per-entry scoring loop: seven NFKD normalizations,
     * two tokenizations and five regex splits, times ~2000 entries, on every
     * keystroke. That was 40-110ms of the search's ~60-150ms, and it is the
     * reason typing in the launcher stuttered.
     */
    function buildScoreRecord(entry: var): var {
        const label = root.normalize(entry.label);
        const key = root.normalize(entry.key);
        const keyParts = key.split(".");
        const lastKey = keyParts.length > 0 ? keyParts[keyParts.length - 1] : "";
        const description = root.normalize(entry.description);
        const fallback = root.normalize(entry.match ?? "");
        const optionLabels = root.normalize(Array.from(entry.options ?? [])
            .map(option => String(option?.label ?? "")).join(" "));
        return {
            entry: entry,
            label: label,
            key: key,
            lastKey: lastKey,
            lastKeyTokens: root.tokens(lastKey),
            keyWords: root.tokens(key),
            description: description,
            // The untranslated strings, so a key someone knows in English stays
            // findable in a translated interface.
            fallback: fallback,
            optionLabels: optionLabels,
            navigation: root.normalize([
                Array.from(entry.aliases ?? []).join(" "),
                entry.pageName ?? "",
                entry.sectionTitle ?? ""
            ].join(" ")),
            keywords: Array.from(entry.keywords ?? []).map(word => root.normalize(word)),
            hasUi: entry.hasUi === true,
            labelWords: root.stemWords(label),
            keyStemWords: root.stemWords(key),
            descriptionWords: root.stemWords(description),
            fallbackWords: root.stemWords(fallback),
            optionWords: root.stemWords(optionLabels)
        };
    }

    // Rebuilt only when the index itself is replaced — a file load or a
    // regeneration, never a keystroke.
    readonly property var scoreIndex: root.entries.map(entry => root.buildScoreRecord(entry))

    /**
     * How well one entry answers a query.
     *
     * `covered` is how much of the question it speaks to, `identity` how much
     * of that came from the entry itself rather than from the page it happens
     * to sit on. Both are needed: a setting whose label is the single word
     * "mode" used to beat the real dark-mode switch for "dark mode", and every
     * option on the Power page used to answer "automatic suspend".
     */
    function scoreRecord(record: var, queryTokens: var, queryNormalized: string): var {
        const hasUi = record.hasUi;

        let score = hasUi ? 40 : 0;
        let covered = 0;
        let identity = 0;

        for (const token of queryTokens) {
            const stem = root.stemOf(token);
            let own = 0;
            if (token === record.label)
                own = Math.max(own, 500);
            else if (record.label.startsWith(token))
                own = Math.max(own, 220);
            else if (record.label.indexOf(token) >= 0)
                own = Math.max(own, 150);
            else if (root.stemHit(stem, record.labelWords))
                own = Math.max(own, 110);

            if (token === record.lastKey || record.lastKeyTokens.indexOf(token) >= 0)
                own = Math.max(own, 180);
            else if (record.keyWords.indexOf(token) >= 0 || record.keyWords.some(word => word.startsWith(token)))
                own = Math.max(own, 120);
            else if (root.stemHit(stem, record.keyStemWords))
                own = Math.max(own, 90);

            if (record.description.indexOf(token) >= 0)
                own = Math.max(own, 120);
            else if (root.stemHit(stem, record.descriptionWords))
                own = Math.max(own, 80);

            if (record.fallback.indexOf(token) >= 0)
                own = Math.max(own, 90);
            else if (root.stemHit(stem, record.fallbackWords))
                own = Math.max(own, 70);

            // The visible option names are the control's own words — someone
            // searching "week" means the Day/Week/Month selector, not whatever
            // else on the page contains the letters. Stronger than page-sharing,
            // weaker than the label itself. Mirrors the generator's score_entry.
            if (record.optionLabels.indexOf(token) >= 0)
                own = Math.max(own, 130);
            else if (root.stemHit(stem, record.optionWords))
                own = Math.max(own, 100);

            // A domain synonym is curated for this entry — "dormir" really is
            // what this switch does — so it counts as the entry's own
            // evidence. It is the bridge that lets someone search in one
            // language an interface that is showing another.
            if (record.keywords.indexOf(token) >= 0)
                own = Math.max(own, 90);

            // Borrowed evidence is not stemmed, and never stands alone.
            // Sharing a page with a word is weak enough already; matching it
            // approximately turns every option on that page into an answer.
            let borrowed = 0;
            if (record.navigation.indexOf(token) >= 0)
                borrowed = Math.max(borrowed, 100);

            const best = Math.max(own, borrowed);
            if (best > 0) {
                covered += 1;
                score += best;
                identity += own;
            }
        }

        let base = score;
        if (queryNormalized.length > 0 && queryNormalized === record.label)
            score += 500;
        if (!hasUi) {
            score = Math.round(score * 0.6);
            base = Math.round(base * 0.6);
        }
        return { score: score, base: base, covered: covered, identity: identity };
    }

    // One slot is enough: the launcher asks the same question several times per
    // keystroke, as late file and revision signals each re-run the result set.
    property string _searchCacheQuery: ""
    property int _searchCacheLimit: -1
    property var _searchCacheResult: []
    onScoreIndexChanged: root._searchCacheLimit = -1

    /**
     * The settings that answer a query, best first and few.
     *
     * Eight results for "automatic suspend" was not eight answers: it was two
     * answers and six things containing the word "suspend".
     */
    function search(query: string, limit = 5): var {
        const queryNormalized = root.normalize(String(query ?? "").trim());
        const effectiveLimit = Math.max(1, Math.min(root.maxResults, Number(limit) || 5));
        if (root._searchCacheLimit === effectiveLimit && root._searchCacheQuery === queryNormalized)
            return root._searchCacheResult;

        const words = root.queryTokens(queryNormalized);
        const found = words.length === 0 ? [] : root._searchScored(words, queryNormalized, effectiveLimit);
        root._searchCacheQuery = queryNormalized;
        root._searchCacheLimit = effectiveLimit;
        root._searchCacheResult = found;
        return found;
    }

    function _searchScored(words: var, queryNormalized: string, effectiveLimit: int): var {
        const scored = [];
        const records = root.scoreIndex;
        for (let i = 0; i < records.length; i++) {
            const verdict = root.scoreRecord(records[i], words, queryNormalized);
            if (verdict.covered === 0 || verdict.identity === 0)
                continue;
            scored.push({ verdict: verdict, entry: records[i].entry });
        }
        if (scored.length === 0)
            return [];

        const bestCoverage = scored.reduce((best, item) => Math.max(best, item.verdict.covered), 0);
        let kept = scored.filter(item => item.verdict.covered === bestCoverage);

        // The floor is measured against the best match *without* its
        // exact-phrase bonus: measuring against the bonus lets one perfect hit
        // push out every other reasonable answer, which is how "Suspend at (%)"
        // vanished from a search for "automatic suspend".
        const topBase = kept.reduce((best, item) => Math.max(best, item.verdict.base), 0);
        kept = kept.filter(item => item.verdict.base >= topBase * root.relevanceFloor);

        kept.sort((left, right) => right.verdict.score - left.verdict.score);
        return kept
            .slice(0, effectiveLimit)
            .map(item => root.settingRef(item.entry, item.verdict.score));
    }

    function get(keys: var): var {
        const wanted = Array.from(keys ?? []).slice(0, 10);
        return wanted.map(key => {
            const entry = root.entryFor(String(key));
            if (!entry)
                return { key: String(key), error: "unknownKey" };
            return root.settingRef(entry);
        });
    }

    function validate(key: string, value: var): var {
        const entry = root.entryFor(key);
        if (!entry)
            return { ok: false, reason: "unknownKey" };
        const type = String(entry.type ?? "unknown");
        if (type === "bool" && typeof value !== "boolean")
            return { ok: false, reason: "expectedBool", entry: entry };
        if (type === "int" && (typeof value !== "number" || !Number.isInteger(value)))
            return { ok: false, reason: "expectedInteger", entry: entry };
        if (type === "real" && (typeof value !== "number" || !Number.isFinite(value)))
            return { ok: false, reason: "expectedNumber", entry: entry };
        if (type === "string" && typeof value !== "string")
            return { ok: false, reason: "expectedString", entry: entry };
        if (type === "enum") {
            const options = Array.from(entry.options ?? []).map(option => option.value);
            if (options.length > 0 && options.indexOf(value) < 0)
                return { ok: false, reason: "outsideOptions", entry: entry };
        }
        const range = entry.range ?? null;
        if (range && typeof value === "number") {
            if (range.from !== null && range.from !== undefined && value < Number(range.from))
                return { ok: false, reason: "belowRange", entry: entry };
            if (range.to !== null && range.to !== undefined && value > Number(range.to))
                return { ok: false, reason: "aboveRange", entry: entry };
            // `stepSize` is how far one click of the spin box moves the value,
            // not a rule about which values are legal. Treating it as a rule
            // refused everything the arrows produced — `battery.suspend` sat
            // at 3, the step is 5, so every press landed on 8, 13, 18 and was
            // rejected — and refused the value already stored, too.
        }
        try {
            const strict = Config.validateNestedValue(key, value);
            if (strict?.ok === false)
                return strict;
        } catch (error) {
            return { ok: false, reason: String(error) };
        }
        return { ok: true, reason: "", value: value, entry: entry };
    }

    /**
     * A refusal in words, for the card that has to show it.
     *
     * `reason` stays a code — the model reads it, and tests pin it — but a
     * code is not something to put in front of someone who just pressed a
     * plus button. This used to print `outsideStep` under the control.
     */
    function reasonText(verdict: var): string {
        const entry = verdict?.entry ?? null;
        const range = entry?.range ?? null;
        switch (String(verdict?.reason ?? "")) {
        case "unknownKey":
            return Translation.tr("There is no such setting.");
        case "expectedBool":
            return Translation.tr("This setting is on or off.");
        case "expectedInteger":
            return Translation.tr("This setting takes a whole number.");
        case "expectedNumber":
            return Translation.tr("This setting takes a number.");
        case "expectedString":
            return Translation.tr("This setting takes text.");
        case "outsideOptions":
            return Translation.tr("Choose one of: %1")
                .arg(Array.from(entry?.options ?? []).map(option => String(option?.label ?? option?.value ?? "")).join(", "));
        case "belowRange":
            return Translation.tr("The lowest this setting goes is %1.").arg(String(range?.from ?? ""));
        case "aboveRange":
            return Translation.tr("The highest this setting goes is %1.").arg(String(range?.to ?? ""));
        }
        const reason = String(verdict?.reason ?? "");
        return reason.length > 0 ? reason : Translation.tr("This value is not valid for this setting.");
    }

    function propose(changes: var): var {
        const preview = [];
        const warnings = [];
        for (const change of Array.from(changes ?? [])) {
            const key = String(change?.key ?? "");
            const verdict = root.validate(key, change?.value);
            const entry = verdict.entry ?? root.entryFor(key);
            const item = {
                key: key,
                label: entry?.label ?? key,
                current: root.currentValue(key),
                proposed: change?.value,
                valid: verdict.ok === true,
                reason: verdict.reason ?? "",
                requiresRestart: entry?.requiresRestart === true
            };
            if (entry?.dependsOn && root.currentValue(entry.dependsOn) !== true) {
                item.dependencyWarning = entry.dependsOn;
                warnings.push(`${key} depends on ${entry.dependsOn}`);
            }
            if (item.requiresRestart)
                warnings.push(`${key} requires restart`);
            preview.push(item);
        }
        return { changes: preview, warnings: warnings, requiresRestart: preview.some(change => change.requiresRestart) };
    }

    function apply(changes: var): var {
        const applied = [];
        const skipped = [];
        for (const change of Array.from(changes ?? [])) {
            const key = String(change?.key ?? "");
            const value = change?.proposed !== undefined ? change.proposed : change?.value;
            const verdict = root.validate(key, value);
            if (!verdict.ok) {
                skipped.push({ key: key, reason: verdict.reason });
                continue;
            }
            try {
                Config.setNestedValue(key, value, true);
                applied.push({ key: key, value: value });
            } catch (error) {
                skipped.push({ key: key, reason: String(error) });
            }
        }
        return { applied: applied, skipped: skipped };
    }

    readonly property FileView indexFile: FileView {
        id: indexFile
        path: root.indexPath
        watchChanges: true
        printErrors: false
        onLoaded: root.ingest(text())
        onLoadFailed: root.rebuild()
    }

    readonly property Process indexCheck: Process {
        id: indexCheck
        command: ["python3", root.generatorPath, "--lang", root.language, "--out", root.indexPath, "check"]
        onExited: exitCode => {
            if (exitCode === 0)
                indexFile.reload();
            else
                root.rebuild();
        }
    }

    readonly property Process indexBuild: Process {
        id: indexBuild
        command: ["python3", root.generatorPath, "--lang", root.language, "--out", root.indexPath, "build"]
        onExited: exitCode => {
            root.rebuilding = false;
            if (exitCode === 0)
                indexFile.reload();
            else
                root.lastError = "settings index build failed";
        }
    }

    // Switching the interface language makes every label in the index wrong,
    // including the section titles the deep-link matches on.
    onLanguageChanged: root.rebuild()

    Component.onCompleted: root.ensureIndex()
}
